// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package portmock

//go:generate minimock -i sprezz/internal/domain/port.FollowersSyncCache -o followers_sync_cache_mock.go -n FollowersSyncCacheMock -p portmock

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// FollowersSyncCacheMock implements mm_port.FollowersSyncCache
type FollowersSyncCacheMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcEvictDigest          func(ctx context.Context, actorIRI string, targetDomain string)
	funcEvictDigestOrigin    string
	inspectFuncEvictDigest   func(ctx context.Context, actorIRI string, targetDomain string)
	afterEvictDigestCounter  uint64
	beforeEvictDigestCounter uint64
	EvictDigestMock          mFollowersSyncCacheMockEvictDigest

	funcGetDigest          func(ctx context.Context, actorIRI string, targetDomain string) (s1 string, b1 bool)
	funcGetDigestOrigin    string
	inspectFuncGetDigest   func(ctx context.Context, actorIRI string, targetDomain string)
	afterGetDigestCounter  uint64
	beforeGetDigestCounter uint64
	GetDigestMock          mFollowersSyncCacheMockGetDigest

	funcSetDigest          func(ctx context.Context, actorIRI string, targetDomain string, digest string)
	funcSetDigestOrigin    string
	inspectFuncSetDigest   func(ctx context.Context, actorIRI string, targetDomain string, digest string)
	afterSetDigestCounter  uint64
	beforeSetDigestCounter uint64
	SetDigestMock          mFollowersSyncCacheMockSetDigest
}

// NewFollowersSyncCacheMock returns a mock for mm_port.FollowersSyncCache
func NewFollowersSyncCacheMock(t minimock.Tester) *FollowersSyncCacheMock {
	m := &FollowersSyncCacheMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.EvictDigestMock = mFollowersSyncCacheMockEvictDigest{mock: m}
	m.EvictDigestMock.callArgs = []*FollowersSyncCacheMockEvictDigestParams{}

	m.GetDigestMock = mFollowersSyncCacheMockGetDigest{mock: m}
	m.GetDigestMock.callArgs = []*FollowersSyncCacheMockGetDigestParams{}

	m.SetDigestMock = mFollowersSyncCacheMockSetDigest{mock: m}
	m.SetDigestMock.callArgs = []*FollowersSyncCacheMockSetDigestParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mFollowersSyncCacheMockEvictDigest struct {
	optional           bool
	mock               *FollowersSyncCacheMock
	defaultExpectation *FollowersSyncCacheMockEvictDigestExpectation
	expectations       []*FollowersSyncCacheMockEvictDigestExpectation

	callArgs []*FollowersSyncCacheMockEvictDigestParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// FollowersSyncCacheMockEvictDigestExpectation specifies expectation struct of the FollowersSyncCache.EvictDigest
type FollowersSyncCacheMockEvictDigestExpectation struct {
	mock               *FollowersSyncCacheMock
	params             *FollowersSyncCacheMockEvictDigestParams
	paramPtrs          *FollowersSyncCacheMockEvictDigestParamPtrs
	expectationOrigins FollowersSyncCacheMockEvictDigestExpectationOrigins

	returnOrigin string
	Counter      uint64
}

// FollowersSyncCacheMockEvictDigestParams contains parameters of the FollowersSyncCache.EvictDigest
type FollowersSyncCacheMockEvictDigestParams struct {
	ctx          context.Context
	actorIRI     string
	targetDomain string
}

// FollowersSyncCacheMockEvictDigestParamPtrs contains pointers to parameters of the FollowersSyncCache.EvictDigest
type FollowersSyncCacheMockEvictDigestParamPtrs struct {
	ctx          *context.Context
	actorIRI     *string
	targetDomain *string
}

// FollowersSyncCacheMockEvictDigestOrigins contains origins of expectations of the FollowersSyncCache.EvictDigest
type FollowersSyncCacheMockEvictDigestExpectationOrigins struct {
	origin             string
	originCtx          string
	originActorIRI     string
	originTargetDomain string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmEvictDigest *mFollowersSyncCacheMockEvictDigest) Optional() *mFollowersSyncCacheMockEvictDigest {
	mmEvictDigest.optional = true
	return mmEvictDigest
}

// Expect sets up expected params for FollowersSyncCache.EvictDigest
func (mmEvictDigest *mFollowersSyncCacheMockEvictDigest) Expect(ctx context.Context, actorIRI string, targetDomain string) *mFollowersSyncCacheMockEvictDigest {
	if mmEvictDigest.mock.funcEvictDigest != nil {
		mmEvictDigest.mock.t.Fatalf("FollowersSyncCacheMock.EvictDigest mock is already set by Set")
	}

	if mmEvictDigest.defaultExpectation == nil {
		mmEvictDigest.defaultExpectation = &FollowersSyncCacheMockEvictDigestExpectation{}
	}

	if mmEvictDigest.defaultExpectation.paramPtrs != nil {
		mmEvictDigest.mock.t.Fatalf("FollowersSyncCacheMock.EvictDigest mock is already set by ExpectParams functions")
	}

	mmEvictDigest.defaultExpectation.params = &FollowersSyncCacheMockEvictDigestParams{ctx, actorIRI, targetDomain}
	mmEvictDigest.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmEvictDigest.expectations {
		if minimock.Equal(e.params, mmEvictDigest.defaultExpectation.params) {
			mmEvictDigest.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmEvictDigest.defaultExpectation.params)
		}
	}

	return mmEvictDigest
}

// ExpectCtxParam1 sets up expected param ctx for FollowersSyncCache.EvictDigest
func (mmEvictDigest *mFollowersSyncCacheMockEvictDigest) ExpectCtxParam1(ctx context.Context) *mFollowersSyncCacheMockEvictDigest {
	if mmEvictDigest.mock.funcEvictDigest != nil {
		mmEvictDigest.mock.t.Fatalf("FollowersSyncCacheMock.EvictDigest mock is already set by Set")
	}

	if mmEvictDigest.defaultExpectation == nil {
		mmEvictDigest.defaultExpectation = &FollowersSyncCacheMockEvictDigestExpectation{}
	}

	if mmEvictDigest.defaultExpectation.params != nil {
		mmEvictDigest.mock.t.Fatalf("FollowersSyncCacheMock.EvictDigest mock is already set by Expect")
	}

	if mmEvictDigest.defaultExpectation.paramPtrs == nil {
		mmEvictDigest.defaultExpectation.paramPtrs = &FollowersSyncCacheMockEvictDigestParamPtrs{}
	}
	mmEvictDigest.defaultExpectation.paramPtrs.ctx = &ctx
	mmEvictDigest.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmEvictDigest
}

// ExpectActorIRIParam2 sets up expected param actorIRI for FollowersSyncCache.EvictDigest
func (mmEvictDigest *mFollowersSyncCacheMockEvictDigest) ExpectActorIRIParam2(actorIRI string) *mFollowersSyncCacheMockEvictDigest {
	if mmEvictDigest.mock.funcEvictDigest != nil {
		mmEvictDigest.mock.t.Fatalf("FollowersSyncCacheMock.EvictDigest mock is already set by Set")
	}

	if mmEvictDigest.defaultExpectation == nil {
		mmEvictDigest.defaultExpectation = &FollowersSyncCacheMockEvictDigestExpectation{}
	}

	if mmEvictDigest.defaultExpectation.params != nil {
		mmEvictDigest.mock.t.Fatalf("FollowersSyncCacheMock.EvictDigest mock is already set by Expect")
	}

	if mmEvictDigest.defaultExpectation.paramPtrs == nil {
		mmEvictDigest.defaultExpectation.paramPtrs = &FollowersSyncCacheMockEvictDigestParamPtrs{}
	}
	mmEvictDigest.defaultExpectation.paramPtrs.actorIRI = &actorIRI
	mmEvictDigest.defaultExpectation.expectationOrigins.originActorIRI = minimock.CallerInfo(1)

	return mmEvictDigest
}

// ExpectTargetDomainParam3 sets up expected param targetDomain for FollowersSyncCache.EvictDigest
func (mmEvictDigest *mFollowersSyncCacheMockEvictDigest) ExpectTargetDomainParam3(targetDomain string) *mFollowersSyncCacheMockEvictDigest {
	if mmEvictDigest.mock.funcEvictDigest != nil {
		mmEvictDigest.mock.t.Fatalf("FollowersSyncCacheMock.EvictDigest mock is already set by Set")
	}

	if mmEvictDigest.defaultExpectation == nil {
		mmEvictDigest.defaultExpectation = &FollowersSyncCacheMockEvictDigestExpectation{}
	}

	if mmEvictDigest.defaultExpectation.params != nil {
		mmEvictDigest.mock.t.Fatalf("FollowersSyncCacheMock.EvictDigest mock is already set by Expect")
	}

	if mmEvictDigest.defaultExpectation.paramPtrs == nil {
		mmEvictDigest.defaultExpectation.paramPtrs = &FollowersSyncCacheMockEvictDigestParamPtrs{}
	}
	mmEvictDigest.defaultExpectation.paramPtrs.targetDomain = &targetDomain
	mmEvictDigest.defaultExpectation.expectationOrigins.originTargetDomain = minimock.CallerInfo(1)

	return mmEvictDigest
}

// Inspect accepts an inspector function that has same arguments as the FollowersSyncCache.EvictDigest
func (mmEvictDigest *mFollowersSyncCacheMockEvictDigest) Inspect(f func(ctx context.Context, actorIRI string, targetDomain string)) *mFollowersSyncCacheMockEvictDigest {
	if mmEvictDigest.mock.inspectFuncEvictDigest != nil {
		mmEvictDigest.mock.t.Fatalf("Inspect function is already set for FollowersSyncCacheMock.EvictDigest")
	}

	mmEvictDigest.mock.inspectFuncEvictDigest = f

	return mmEvictDigest
}

// Return sets up results that will be returned by FollowersSyncCache.EvictDigest
func (mmEvictDigest *mFollowersSyncCacheMockEvictDigest) Return() *FollowersSyncCacheMock {
	if mmEvictDigest.mock.funcEvictDigest != nil {
		mmEvictDigest.mock.t.Fatalf("FollowersSyncCacheMock.EvictDigest mock is already set by Set")
	}

	if mmEvictDigest.defaultExpectation == nil {
		mmEvictDigest.defaultExpectation = &FollowersSyncCacheMockEvictDigestExpectation{mock: mmEvictDigest.mock}
	}

	mmEvictDigest.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmEvictDigest.mock
}

// Set uses given function f to mock the FollowersSyncCache.EvictDigest method
func (mmEvictDigest *mFollowersSyncCacheMockEvictDigest) Set(f func(ctx context.Context, actorIRI string, targetDomain string)) *FollowersSyncCacheMock {
	if mmEvictDigest.defaultExpectation != nil {
		mmEvictDigest.mock.t.Fatalf("Default expectation is already set for the FollowersSyncCache.EvictDigest method")
	}

	if len(mmEvictDigest.expectations) > 0 {
		mmEvictDigest.mock.t.Fatalf("Some expectations are already set for the FollowersSyncCache.EvictDigest method")
	}

	mmEvictDigest.mock.funcEvictDigest = f
	mmEvictDigest.mock.funcEvictDigestOrigin = minimock.CallerInfo(1)
	return mmEvictDigest.mock
}

// When sets expectation for the FollowersSyncCache.EvictDigest which will trigger the result defined by the following
// Then helper
func (mmEvictDigest *mFollowersSyncCacheMockEvictDigest) When(ctx context.Context, actorIRI string, targetDomain string) *FollowersSyncCacheMockEvictDigestExpectation {
	if mmEvictDigest.mock.funcEvictDigest != nil {
		mmEvictDigest.mock.t.Fatalf("FollowersSyncCacheMock.EvictDigest mock is already set by Set")
	}

	expectation := &FollowersSyncCacheMockEvictDigestExpectation{
		mock:               mmEvictDigest.mock,
		params:             &FollowersSyncCacheMockEvictDigestParams{ctx, actorIRI, targetDomain},
		expectationOrigins: FollowersSyncCacheMockEvictDigestExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmEvictDigest.expectations = append(mmEvictDigest.expectations, expectation)
	return expectation
}

// Then sets up FollowersSyncCache.EvictDigest return parameters for the expectation previously defined by the When method

func (e *FollowersSyncCacheMockEvictDigestExpectation) Then() *FollowersSyncCacheMock {
	return e.mock
}

// Times sets number of times FollowersSyncCache.EvictDigest should be invoked
func (mmEvictDigest *mFollowersSyncCacheMockEvictDigest) Times(n uint64) *mFollowersSyncCacheMockEvictDigest {
	if n == 0 {
		mmEvictDigest.mock.t.Fatalf("Times of FollowersSyncCacheMock.EvictDigest mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmEvictDigest.expectedInvocations, n)
	mmEvictDigest.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmEvictDigest
}

func (mmEvictDigest *mFollowersSyncCacheMockEvictDigest) invocationsDone() bool {
	if len(mmEvictDigest.expectations) == 0 && mmEvictDigest.defaultExpectation == nil && mmEvictDigest.mock.funcEvictDigest == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmEvictDigest.mock.afterEvictDigestCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmEvictDigest.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// EvictDigest implements mm_port.FollowersSyncCache
func (mmEvictDigest *FollowersSyncCacheMock) EvictDigest(ctx context.Context, actorIRI string, targetDomain string) {
	mm_atomic.AddUint64(&mmEvictDigest.beforeEvictDigestCounter, 1)
	defer mm_atomic.AddUint64(&mmEvictDigest.afterEvictDigestCounter, 1)

	mmEvictDigest.t.Helper()

	if mmEvictDigest.inspectFuncEvictDigest != nil {
		mmEvictDigest.inspectFuncEvictDigest(ctx, actorIRI, targetDomain)
	}

	mm_params := FollowersSyncCacheMockEvictDigestParams{ctx, actorIRI, targetDomain}

	// Record call args
	mmEvictDigest.EvictDigestMock.mutex.Lock()
	mmEvictDigest.EvictDigestMock.callArgs = append(mmEvictDigest.EvictDigestMock.callArgs, &mm_params)
	mmEvictDigest.EvictDigestMock.mutex.Unlock()

	for _, e := range mmEvictDigest.EvictDigestMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return
		}
	}

	if mmEvictDigest.EvictDigestMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmEvictDigest.EvictDigestMock.defaultExpectation.Counter, 1)
		mm_want := mmEvictDigest.EvictDigestMock.defaultExpectation.params
		mm_want_ptrs := mmEvictDigest.EvictDigestMock.defaultExpectation.paramPtrs

		mm_got := FollowersSyncCacheMockEvictDigestParams{ctx, actorIRI, targetDomain}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmEvictDigest.t.Errorf("FollowersSyncCacheMock.EvictDigest got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmEvictDigest.EvictDigestMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.actorIRI != nil && !minimock.Equal(*mm_want_ptrs.actorIRI, mm_got.actorIRI) {
				mmEvictDigest.t.Errorf("FollowersSyncCacheMock.EvictDigest got unexpected parameter actorIRI, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmEvictDigest.EvictDigestMock.defaultExpectation.expectationOrigins.originActorIRI, *mm_want_ptrs.actorIRI, mm_got.actorIRI, minimock.Diff(*mm_want_ptrs.actorIRI, mm_got.actorIRI))
			}

			if mm_want_ptrs.targetDomain != nil && !minimock.Equal(*mm_want_ptrs.targetDomain, mm_got.targetDomain) {
				mmEvictDigest.t.Errorf("FollowersSyncCacheMock.EvictDigest got unexpected parameter targetDomain, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmEvictDigest.EvictDigestMock.defaultExpectation.expectationOrigins.originTargetDomain, *mm_want_ptrs.targetDomain, mm_got.targetDomain, minimock.Diff(*mm_want_ptrs.targetDomain, mm_got.targetDomain))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmEvictDigest.t.Errorf("FollowersSyncCacheMock.EvictDigest got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmEvictDigest.EvictDigestMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		return

	}
	if mmEvictDigest.funcEvictDigest != nil {
		mmEvictDigest.funcEvictDigest(ctx, actorIRI, targetDomain)
		return
	}
	mmEvictDigest.t.Fatalf("Unexpected call to FollowersSyncCacheMock.EvictDigest. %v %v %v", ctx, actorIRI, targetDomain)

}

// EvictDigestAfterCounter returns a count of finished FollowersSyncCacheMock.EvictDigest invocations
func (mmEvictDigest *FollowersSyncCacheMock) EvictDigestAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmEvictDigest.afterEvictDigestCounter)
}

// EvictDigestBeforeCounter returns a count of FollowersSyncCacheMock.EvictDigest invocations
func (mmEvictDigest *FollowersSyncCacheMock) EvictDigestBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmEvictDigest.beforeEvictDigestCounter)
}

// Calls returns a list of arguments used in each call to FollowersSyncCacheMock.EvictDigest.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmEvictDigest *mFollowersSyncCacheMockEvictDigest) Calls() []*FollowersSyncCacheMockEvictDigestParams {
	mmEvictDigest.mutex.RLock()

	argCopy := make([]*FollowersSyncCacheMockEvictDigestParams, len(mmEvictDigest.callArgs))
	copy(argCopy, mmEvictDigest.callArgs)

	mmEvictDigest.mutex.RUnlock()

	return argCopy
}

// MinimockEvictDigestDone returns true if the count of the EvictDigest invocations corresponds
// the number of defined expectations
func (m *FollowersSyncCacheMock) MinimockEvictDigestDone() bool {
	if m.EvictDigestMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.EvictDigestMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.EvictDigestMock.invocationsDone()
}

// MinimockEvictDigestInspect logs each unmet expectation
func (m *FollowersSyncCacheMock) MinimockEvictDigestInspect() {
	for _, e := range m.EvictDigestMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to FollowersSyncCacheMock.EvictDigest at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterEvictDigestCounter := mm_atomic.LoadUint64(&m.afterEvictDigestCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.EvictDigestMock.defaultExpectation != nil && afterEvictDigestCounter < 1 {
		if m.EvictDigestMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to FollowersSyncCacheMock.EvictDigest at\n%s", m.EvictDigestMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to FollowersSyncCacheMock.EvictDigest at\n%s with params: %#v", m.EvictDigestMock.defaultExpectation.expectationOrigins.origin, *m.EvictDigestMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcEvictDigest != nil && afterEvictDigestCounter < 1 {
		m.t.Errorf("Expected call to FollowersSyncCacheMock.EvictDigest at\n%s", m.funcEvictDigestOrigin)
	}

	if !m.EvictDigestMock.invocationsDone() && afterEvictDigestCounter > 0 {
		m.t.Errorf("Expected %d calls to FollowersSyncCacheMock.EvictDigest at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.EvictDigestMock.expectedInvocations), m.EvictDigestMock.expectedInvocationsOrigin, afterEvictDigestCounter)
	}
}

type mFollowersSyncCacheMockGetDigest struct {
	optional           bool
	mock               *FollowersSyncCacheMock
	defaultExpectation *FollowersSyncCacheMockGetDigestExpectation
	expectations       []*FollowersSyncCacheMockGetDigestExpectation

	callArgs []*FollowersSyncCacheMockGetDigestParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// FollowersSyncCacheMockGetDigestExpectation specifies expectation struct of the FollowersSyncCache.GetDigest
type FollowersSyncCacheMockGetDigestExpectation struct {
	mock               *FollowersSyncCacheMock
	params             *FollowersSyncCacheMockGetDigestParams
	paramPtrs          *FollowersSyncCacheMockGetDigestParamPtrs
	expectationOrigins FollowersSyncCacheMockGetDigestExpectationOrigins
	results            *FollowersSyncCacheMockGetDigestResults
	returnOrigin       string
	Counter            uint64
}

// FollowersSyncCacheMockGetDigestParams contains parameters of the FollowersSyncCache.GetDigest
type FollowersSyncCacheMockGetDigestParams struct {
	ctx          context.Context
	actorIRI     string
	targetDomain string
}

// FollowersSyncCacheMockGetDigestParamPtrs contains pointers to parameters of the FollowersSyncCache.GetDigest
type FollowersSyncCacheMockGetDigestParamPtrs struct {
	ctx          *context.Context
	actorIRI     *string
	targetDomain *string
}

// FollowersSyncCacheMockGetDigestResults contains results of the FollowersSyncCache.GetDigest
type FollowersSyncCacheMockGetDigestResults struct {
	s1 string
	b1 bool
}

// FollowersSyncCacheMockGetDigestOrigins contains origins of expectations of the FollowersSyncCache.GetDigest
type FollowersSyncCacheMockGetDigestExpectationOrigins struct {
	origin             string
	originCtx          string
	originActorIRI     string
	originTargetDomain string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetDigest *mFollowersSyncCacheMockGetDigest) Optional() *mFollowersSyncCacheMockGetDigest {
	mmGetDigest.optional = true
	return mmGetDigest
}

// Expect sets up expected params for FollowersSyncCache.GetDigest
func (mmGetDigest *mFollowersSyncCacheMockGetDigest) Expect(ctx context.Context, actorIRI string, targetDomain string) *mFollowersSyncCacheMockGetDigest {
	if mmGetDigest.mock.funcGetDigest != nil {
		mmGetDigest.mock.t.Fatalf("FollowersSyncCacheMock.GetDigest mock is already set by Set")
	}

	if mmGetDigest.defaultExpectation == nil {
		mmGetDigest.defaultExpectation = &FollowersSyncCacheMockGetDigestExpectation{}
	}

	if mmGetDigest.defaultExpectation.paramPtrs != nil {
		mmGetDigest.mock.t.Fatalf("FollowersSyncCacheMock.GetDigest mock is already set by ExpectParams functions")
	}

	mmGetDigest.defaultExpectation.params = &FollowersSyncCacheMockGetDigestParams{ctx, actorIRI, targetDomain}
	mmGetDigest.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetDigest.expectations {
		if minimock.Equal(e.params, mmGetDigest.defaultExpectation.params) {
			mmGetDigest.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetDigest.defaultExpectation.params)
		}
	}

	return mmGetDigest
}

// ExpectCtxParam1 sets up expected param ctx for FollowersSyncCache.GetDigest
func (mmGetDigest *mFollowersSyncCacheMockGetDigest) ExpectCtxParam1(ctx context.Context) *mFollowersSyncCacheMockGetDigest {
	if mmGetDigest.mock.funcGetDigest != nil {
		mmGetDigest.mock.t.Fatalf("FollowersSyncCacheMock.GetDigest mock is already set by Set")
	}

	if mmGetDigest.defaultExpectation == nil {
		mmGetDigest.defaultExpectation = &FollowersSyncCacheMockGetDigestExpectation{}
	}

	if mmGetDigest.defaultExpectation.params != nil {
		mmGetDigest.mock.t.Fatalf("FollowersSyncCacheMock.GetDigest mock is already set by Expect")
	}

	if mmGetDigest.defaultExpectation.paramPtrs == nil {
		mmGetDigest.defaultExpectation.paramPtrs = &FollowersSyncCacheMockGetDigestParamPtrs{}
	}
	mmGetDigest.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetDigest.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetDigest
}

// ExpectActorIRIParam2 sets up expected param actorIRI for FollowersSyncCache.GetDigest
func (mmGetDigest *mFollowersSyncCacheMockGetDigest) ExpectActorIRIParam2(actorIRI string) *mFollowersSyncCacheMockGetDigest {
	if mmGetDigest.mock.funcGetDigest != nil {
		mmGetDigest.mock.t.Fatalf("FollowersSyncCacheMock.GetDigest mock is already set by Set")
	}

	if mmGetDigest.defaultExpectation == nil {
		mmGetDigest.defaultExpectation = &FollowersSyncCacheMockGetDigestExpectation{}
	}

	if mmGetDigest.defaultExpectation.params != nil {
		mmGetDigest.mock.t.Fatalf("FollowersSyncCacheMock.GetDigest mock is already set by Expect")
	}

	if mmGetDigest.defaultExpectation.paramPtrs == nil {
		mmGetDigest.defaultExpectation.paramPtrs = &FollowersSyncCacheMockGetDigestParamPtrs{}
	}
	mmGetDigest.defaultExpectation.paramPtrs.actorIRI = &actorIRI
	mmGetDigest.defaultExpectation.expectationOrigins.originActorIRI = minimock.CallerInfo(1)

	return mmGetDigest
}

// ExpectTargetDomainParam3 sets up expected param targetDomain for FollowersSyncCache.GetDigest
func (mmGetDigest *mFollowersSyncCacheMockGetDigest) ExpectTargetDomainParam3(targetDomain string) *mFollowersSyncCacheMockGetDigest {
	if mmGetDigest.mock.funcGetDigest != nil {
		mmGetDigest.mock.t.Fatalf("FollowersSyncCacheMock.GetDigest mock is already set by Set")
	}

	if mmGetDigest.defaultExpectation == nil {
		mmGetDigest.defaultExpectation = &FollowersSyncCacheMockGetDigestExpectation{}
	}

	if mmGetDigest.defaultExpectation.params != nil {
		mmGetDigest.mock.t.Fatalf("FollowersSyncCacheMock.GetDigest mock is already set by Expect")
	}

	if mmGetDigest.defaultExpectation.paramPtrs == nil {
		mmGetDigest.defaultExpectation.paramPtrs = &FollowersSyncCacheMockGetDigestParamPtrs{}
	}
	mmGetDigest.defaultExpectation.paramPtrs.targetDomain = &targetDomain
	mmGetDigest.defaultExpectation.expectationOrigins.originTargetDomain = minimock.CallerInfo(1)

	return mmGetDigest
}

// Inspect accepts an inspector function that has same arguments as the FollowersSyncCache.GetDigest
func (mmGetDigest *mFollowersSyncCacheMockGetDigest) Inspect(f func(ctx context.Context, actorIRI string, targetDomain string)) *mFollowersSyncCacheMockGetDigest {
	if mmGetDigest.mock.inspectFuncGetDigest != nil {
		mmGetDigest.mock.t.Fatalf("Inspect function is already set for FollowersSyncCacheMock.GetDigest")
	}

	mmGetDigest.mock.inspectFuncGetDigest = f

	return mmGetDigest
}

// Return sets up results that will be returned by FollowersSyncCache.GetDigest
func (mmGetDigest *mFollowersSyncCacheMockGetDigest) Return(s1 string, b1 bool) *FollowersSyncCacheMock {
	if mmGetDigest.mock.funcGetDigest != nil {
		mmGetDigest.mock.t.Fatalf("FollowersSyncCacheMock.GetDigest mock is already set by Set")
	}

	if mmGetDigest.defaultExpectation == nil {
		mmGetDigest.defaultExpectation = &FollowersSyncCacheMockGetDigestExpectation{mock: mmGetDigest.mock}
	}
	mmGetDigest.defaultExpectation.results = &FollowersSyncCacheMockGetDigestResults{s1, b1}
	mmGetDigest.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetDigest.mock
}

// Set uses given function f to mock the FollowersSyncCache.GetDigest method
func (mmGetDigest *mFollowersSyncCacheMockGetDigest) Set(f func(ctx context.Context, actorIRI string, targetDomain string) (s1 string, b1 bool)) *FollowersSyncCacheMock {
	if mmGetDigest.defaultExpectation != nil {
		mmGetDigest.mock.t.Fatalf("Default expectation is already set for the FollowersSyncCache.GetDigest method")
	}

	if len(mmGetDigest.expectations) > 0 {
		mmGetDigest.mock.t.Fatalf("Some expectations are already set for the FollowersSyncCache.GetDigest method")
	}

	mmGetDigest.mock.funcGetDigest = f
	mmGetDigest.mock.funcGetDigestOrigin = minimock.CallerInfo(1)
	return mmGetDigest.mock
}

// When sets expectation for the FollowersSyncCache.GetDigest which will trigger the result defined by the following
// Then helper
func (mmGetDigest *mFollowersSyncCacheMockGetDigest) When(ctx context.Context, actorIRI string, targetDomain string) *FollowersSyncCacheMockGetDigestExpectation {
	if mmGetDigest.mock.funcGetDigest != nil {
		mmGetDigest.mock.t.Fatalf("FollowersSyncCacheMock.GetDigest mock is already set by Set")
	}

	expectation := &FollowersSyncCacheMockGetDigestExpectation{
		mock:               mmGetDigest.mock,
		params:             &FollowersSyncCacheMockGetDigestParams{ctx, actorIRI, targetDomain},
		expectationOrigins: FollowersSyncCacheMockGetDigestExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetDigest.expectations = append(mmGetDigest.expectations, expectation)
	return expectation
}

// Then sets up FollowersSyncCache.GetDigest return parameters for the expectation previously defined by the When method
func (e *FollowersSyncCacheMockGetDigestExpectation) Then(s1 string, b1 bool) *FollowersSyncCacheMock {
	e.results = &FollowersSyncCacheMockGetDigestResults{s1, b1}
	return e.mock
}

// Times sets number of times FollowersSyncCache.GetDigest should be invoked
func (mmGetDigest *mFollowersSyncCacheMockGetDigest) Times(n uint64) *mFollowersSyncCacheMockGetDigest {
	if n == 0 {
		mmGetDigest.mock.t.Fatalf("Times of FollowersSyncCacheMock.GetDigest mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetDigest.expectedInvocations, n)
	mmGetDigest.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetDigest
}

func (mmGetDigest *mFollowersSyncCacheMockGetDigest) invocationsDone() bool {
	if len(mmGetDigest.expectations) == 0 && mmGetDigest.defaultExpectation == nil && mmGetDigest.mock.funcGetDigest == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetDigest.mock.afterGetDigestCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetDigest.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetDigest implements mm_port.FollowersSyncCache
func (mmGetDigest *FollowersSyncCacheMock) GetDigest(ctx context.Context, actorIRI string, targetDomain string) (s1 string, b1 bool) {
	mm_atomic.AddUint64(&mmGetDigest.beforeGetDigestCounter, 1)
	defer mm_atomic.AddUint64(&mmGetDigest.afterGetDigestCounter, 1)

	mmGetDigest.t.Helper()

	if mmGetDigest.inspectFuncGetDigest != nil {
		mmGetDigest.inspectFuncGetDigest(ctx, actorIRI, targetDomain)
	}

	mm_params := FollowersSyncCacheMockGetDigestParams{ctx, actorIRI, targetDomain}

	// Record call args
	mmGetDigest.GetDigestMock.mutex.Lock()
	mmGetDigest.GetDigestMock.callArgs = append(mmGetDigest.GetDigestMock.callArgs, &mm_params)
	mmGetDigest.GetDigestMock.mutex.Unlock()

	for _, e := range mmGetDigest.GetDigestMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.b1
		}
	}

	if mmGetDigest.GetDigestMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetDigest.GetDigestMock.defaultExpectation.Counter, 1)
		mm_want := mmGetDigest.GetDigestMock.defaultExpectation.params
		mm_want_ptrs := mmGetDigest.GetDigestMock.defaultExpectation.paramPtrs

		mm_got := FollowersSyncCacheMockGetDigestParams{ctx, actorIRI, targetDomain}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetDigest.t.Errorf("FollowersSyncCacheMock.GetDigest got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetDigest.GetDigestMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.actorIRI != nil && !minimock.Equal(*mm_want_ptrs.actorIRI, mm_got.actorIRI) {
				mmGetDigest.t.Errorf("FollowersSyncCacheMock.GetDigest got unexpected parameter actorIRI, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetDigest.GetDigestMock.defaultExpectation.expectationOrigins.originActorIRI, *mm_want_ptrs.actorIRI, mm_got.actorIRI, minimock.Diff(*mm_want_ptrs.actorIRI, mm_got.actorIRI))
			}

			if mm_want_ptrs.targetDomain != nil && !minimock.Equal(*mm_want_ptrs.targetDomain, mm_got.targetDomain) {
				mmGetDigest.t.Errorf("FollowersSyncCacheMock.GetDigest got unexpected parameter targetDomain, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetDigest.GetDigestMock.defaultExpectation.expectationOrigins.originTargetDomain, *mm_want_ptrs.targetDomain, mm_got.targetDomain, minimock.Diff(*mm_want_ptrs.targetDomain, mm_got.targetDomain))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetDigest.t.Errorf("FollowersSyncCacheMock.GetDigest got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetDigest.GetDigestMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetDigest.GetDigestMock.defaultExpectation.results
		if mm_results == nil {
			mmGetDigest.t.Fatal("No results are set for the FollowersSyncCacheMock.GetDigest")
		}
		return (*mm_results).s1, (*mm_results).b1
	}
	if mmGetDigest.funcGetDigest != nil {
		return mmGetDigest.funcGetDigest(ctx, actorIRI, targetDomain)
	}
	mmGetDigest.t.Fatalf("Unexpected call to FollowersSyncCacheMock.GetDigest. %v %v %v", ctx, actorIRI, targetDomain)
	return
}

// GetDigestAfterCounter returns a count of finished FollowersSyncCacheMock.GetDigest invocations
func (mmGetDigest *FollowersSyncCacheMock) GetDigestAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetDigest.afterGetDigestCounter)
}

// GetDigestBeforeCounter returns a count of FollowersSyncCacheMock.GetDigest invocations
func (mmGetDigest *FollowersSyncCacheMock) GetDigestBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetDigest.beforeGetDigestCounter)
}

// Calls returns a list of arguments used in each call to FollowersSyncCacheMock.GetDigest.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetDigest *mFollowersSyncCacheMockGetDigest) Calls() []*FollowersSyncCacheMockGetDigestParams {
	mmGetDigest.mutex.RLock()

	argCopy := make([]*FollowersSyncCacheMockGetDigestParams, len(mmGetDigest.callArgs))
	copy(argCopy, mmGetDigest.callArgs)

	mmGetDigest.mutex.RUnlock()

	return argCopy
}

// MinimockGetDigestDone returns true if the count of the GetDigest invocations corresponds
// the number of defined expectations
func (m *FollowersSyncCacheMock) MinimockGetDigestDone() bool {
	if m.GetDigestMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetDigestMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetDigestMock.invocationsDone()
}

// MinimockGetDigestInspect logs each unmet expectation
func (m *FollowersSyncCacheMock) MinimockGetDigestInspect() {
	for _, e := range m.GetDigestMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to FollowersSyncCacheMock.GetDigest at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetDigestCounter := mm_atomic.LoadUint64(&m.afterGetDigestCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetDigestMock.defaultExpectation != nil && afterGetDigestCounter < 1 {
		if m.GetDigestMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to FollowersSyncCacheMock.GetDigest at\n%s", m.GetDigestMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to FollowersSyncCacheMock.GetDigest at\n%s with params: %#v", m.GetDigestMock.defaultExpectation.expectationOrigins.origin, *m.GetDigestMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetDigest != nil && afterGetDigestCounter < 1 {
		m.t.Errorf("Expected call to FollowersSyncCacheMock.GetDigest at\n%s", m.funcGetDigestOrigin)
	}

	if !m.GetDigestMock.invocationsDone() && afterGetDigestCounter > 0 {
		m.t.Errorf("Expected %d calls to FollowersSyncCacheMock.GetDigest at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetDigestMock.expectedInvocations), m.GetDigestMock.expectedInvocationsOrigin, afterGetDigestCounter)
	}
}

type mFollowersSyncCacheMockSetDigest struct {
	optional           bool
	mock               *FollowersSyncCacheMock
	defaultExpectation *FollowersSyncCacheMockSetDigestExpectation
	expectations       []*FollowersSyncCacheMockSetDigestExpectation

	callArgs []*FollowersSyncCacheMockSetDigestParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// FollowersSyncCacheMockSetDigestExpectation specifies expectation struct of the FollowersSyncCache.SetDigest
type FollowersSyncCacheMockSetDigestExpectation struct {
	mock               *FollowersSyncCacheMock
	params             *FollowersSyncCacheMockSetDigestParams
	paramPtrs          *FollowersSyncCacheMockSetDigestParamPtrs
	expectationOrigins FollowersSyncCacheMockSetDigestExpectationOrigins

	returnOrigin string
	Counter      uint64
}

// FollowersSyncCacheMockSetDigestParams contains parameters of the FollowersSyncCache.SetDigest
type FollowersSyncCacheMockSetDigestParams struct {
	ctx          context.Context
	actorIRI     string
	targetDomain string
	digest       string
}

// FollowersSyncCacheMockSetDigestParamPtrs contains pointers to parameters of the FollowersSyncCache.SetDigest
type FollowersSyncCacheMockSetDigestParamPtrs struct {
	ctx          *context.Context
	actorIRI     *string
	targetDomain *string
	digest       *string
}

// FollowersSyncCacheMockSetDigestOrigins contains origins of expectations of the FollowersSyncCache.SetDigest
type FollowersSyncCacheMockSetDigestExpectationOrigins struct {
	origin             string
	originCtx          string
	originActorIRI     string
	originTargetDomain string
	originDigest       string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSetDigest *mFollowersSyncCacheMockSetDigest) Optional() *mFollowersSyncCacheMockSetDigest {
	mmSetDigest.optional = true
	return mmSetDigest
}

// Expect sets up expected params for FollowersSyncCache.SetDigest
func (mmSetDigest *mFollowersSyncCacheMockSetDigest) Expect(ctx context.Context, actorIRI string, targetDomain string, digest string) *mFollowersSyncCacheMockSetDigest {
	if mmSetDigest.mock.funcSetDigest != nil {
		mmSetDigest.mock.t.Fatalf("FollowersSyncCacheMock.SetDigest mock is already set by Set")
	}

	if mmSetDigest.defaultExpectation == nil {
		mmSetDigest.defaultExpectation = &FollowersSyncCacheMockSetDigestExpectation{}
	}

	if mmSetDigest.defaultExpectation.paramPtrs != nil {
		mmSetDigest.mock.t.Fatalf("FollowersSyncCacheMock.SetDigest mock is already set by ExpectParams functions")
	}

	mmSetDigest.defaultExpectation.params = &FollowersSyncCacheMockSetDigestParams{ctx, actorIRI, targetDomain, digest}
	mmSetDigest.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSetDigest.expectations {
		if minimock.Equal(e.params, mmSetDigest.defaultExpectation.params) {
			mmSetDigest.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSetDigest.defaultExpectation.params)
		}
	}

	return mmSetDigest
}

// ExpectCtxParam1 sets up expected param ctx for FollowersSyncCache.SetDigest
func (mmSetDigest *mFollowersSyncCacheMockSetDigest) ExpectCtxParam1(ctx context.Context) *mFollowersSyncCacheMockSetDigest {
	if mmSetDigest.mock.funcSetDigest != nil {
		mmSetDigest.mock.t.Fatalf("FollowersSyncCacheMock.SetDigest mock is already set by Set")
	}

	if mmSetDigest.defaultExpectation == nil {
		mmSetDigest.defaultExpectation = &FollowersSyncCacheMockSetDigestExpectation{}
	}

	if mmSetDigest.defaultExpectation.params != nil {
		mmSetDigest.mock.t.Fatalf("FollowersSyncCacheMock.SetDigest mock is already set by Expect")
	}

	if mmSetDigest.defaultExpectation.paramPtrs == nil {
		mmSetDigest.defaultExpectation.paramPtrs = &FollowersSyncCacheMockSetDigestParamPtrs{}
	}
	mmSetDigest.defaultExpectation.paramPtrs.ctx = &ctx
	mmSetDigest.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSetDigest
}

// ExpectActorIRIParam2 sets up expected param actorIRI for FollowersSyncCache.SetDigest
func (mmSetDigest *mFollowersSyncCacheMockSetDigest) ExpectActorIRIParam2(actorIRI string) *mFollowersSyncCacheMockSetDigest {
	if mmSetDigest.mock.funcSetDigest != nil {
		mmSetDigest.mock.t.Fatalf("FollowersSyncCacheMock.SetDigest mock is already set by Set")
	}

	if mmSetDigest.defaultExpectation == nil {
		mmSetDigest.defaultExpectation = &FollowersSyncCacheMockSetDigestExpectation{}
	}

	if mmSetDigest.defaultExpectation.params != nil {
		mmSetDigest.mock.t.Fatalf("FollowersSyncCacheMock.SetDigest mock is already set by Expect")
	}

	if mmSetDigest.defaultExpectation.paramPtrs == nil {
		mmSetDigest.defaultExpectation.paramPtrs = &FollowersSyncCacheMockSetDigestParamPtrs{}
	}
	mmSetDigest.defaultExpectation.paramPtrs.actorIRI = &actorIRI
	mmSetDigest.defaultExpectation.expectationOrigins.originActorIRI = minimock.CallerInfo(1)

	return mmSetDigest
}

// ExpectTargetDomainParam3 sets up expected param targetDomain for FollowersSyncCache.SetDigest
func (mmSetDigest *mFollowersSyncCacheMockSetDigest) ExpectTargetDomainParam3(targetDomain string) *mFollowersSyncCacheMockSetDigest {
	if mmSetDigest.mock.funcSetDigest != nil {
		mmSetDigest.mock.t.Fatalf("FollowersSyncCacheMock.SetDigest mock is already set by Set")
	}

	if mmSetDigest.defaultExpectation == nil {
		mmSetDigest.defaultExpectation = &FollowersSyncCacheMockSetDigestExpectation{}
	}

	if mmSetDigest.defaultExpectation.params != nil {
		mmSetDigest.mock.t.Fatalf("FollowersSyncCacheMock.SetDigest mock is already set by Expect")
	}

	if mmSetDigest.defaultExpectation.paramPtrs == nil {
		mmSetDigest.defaultExpectation.paramPtrs = &FollowersSyncCacheMockSetDigestParamPtrs{}
	}
	mmSetDigest.defaultExpectation.paramPtrs.targetDomain = &targetDomain
	mmSetDigest.defaultExpectation.expectationOrigins.originTargetDomain = minimock.CallerInfo(1)

	return mmSetDigest
}

// ExpectDigestParam4 sets up expected param digest for FollowersSyncCache.SetDigest
func (mmSetDigest *mFollowersSyncCacheMockSetDigest) ExpectDigestParam4(digest string) *mFollowersSyncCacheMockSetDigest {
	if mmSetDigest.mock.funcSetDigest != nil {
		mmSetDigest.mock.t.Fatalf("FollowersSyncCacheMock.SetDigest mock is already set by Set")
	}

	if mmSetDigest.defaultExpectation == nil {
		mmSetDigest.defaultExpectation = &FollowersSyncCacheMockSetDigestExpectation{}
	}

	if mmSetDigest.defaultExpectation.params != nil {
		mmSetDigest.mock.t.Fatalf("FollowersSyncCacheMock.SetDigest mock is already set by Expect")
	}

	if mmSetDigest.defaultExpectation.paramPtrs == nil {
		mmSetDigest.defaultExpectation.paramPtrs = &FollowersSyncCacheMockSetDigestParamPtrs{}
	}
	mmSetDigest.defaultExpectation.paramPtrs.digest = &digest
	mmSetDigest.defaultExpectation.expectationOrigins.originDigest = minimock.CallerInfo(1)

	return mmSetDigest
}

// Inspect accepts an inspector function that has same arguments as the FollowersSyncCache.SetDigest
func (mmSetDigest *mFollowersSyncCacheMockSetDigest) Inspect(f func(ctx context.Context, actorIRI string, targetDomain string, digest string)) *mFollowersSyncCacheMockSetDigest {
	if mmSetDigest.mock.inspectFuncSetDigest != nil {
		mmSetDigest.mock.t.Fatalf("Inspect function is already set for FollowersSyncCacheMock.SetDigest")
	}

	mmSetDigest.mock.inspectFuncSetDigest = f

	return mmSetDigest
}

// Return sets up results that will be returned by FollowersSyncCache.SetDigest
func (mmSetDigest *mFollowersSyncCacheMockSetDigest) Return() *FollowersSyncCacheMock {
	if mmSetDigest.mock.funcSetDigest != nil {
		mmSetDigest.mock.t.Fatalf("FollowersSyncCacheMock.SetDigest mock is already set by Set")
	}

	if mmSetDigest.defaultExpectation == nil {
		mmSetDigest.defaultExpectation = &FollowersSyncCacheMockSetDigestExpectation{mock: mmSetDigest.mock}
	}

	mmSetDigest.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSetDigest.mock
}

// Set uses given function f to mock the FollowersSyncCache.SetDigest method
func (mmSetDigest *mFollowersSyncCacheMockSetDigest) Set(f func(ctx context.Context, actorIRI string, targetDomain string, digest string)) *FollowersSyncCacheMock {
	if mmSetDigest.defaultExpectation != nil {
		mmSetDigest.mock.t.Fatalf("Default expectation is already set for the FollowersSyncCache.SetDigest method")
	}

	if len(mmSetDigest.expectations) > 0 {
		mmSetDigest.mock.t.Fatalf("Some expectations are already set for the FollowersSyncCache.SetDigest method")
	}

	mmSetDigest.mock.funcSetDigest = f
	mmSetDigest.mock.funcSetDigestOrigin = minimock.CallerInfo(1)
	return mmSetDigest.mock
}

// When sets expectation for the FollowersSyncCache.SetDigest which will trigger the result defined by the following
// Then helper
func (mmSetDigest *mFollowersSyncCacheMockSetDigest) When(ctx context.Context, actorIRI string, targetDomain string, digest string) *FollowersSyncCacheMockSetDigestExpectation {
	if mmSetDigest.mock.funcSetDigest != nil {
		mmSetDigest.mock.t.Fatalf("FollowersSyncCacheMock.SetDigest mock is already set by Set")
	}

	expectation := &FollowersSyncCacheMockSetDigestExpectation{
		mock:               mmSetDigest.mock,
		params:             &FollowersSyncCacheMockSetDigestParams{ctx, actorIRI, targetDomain, digest},
		expectationOrigins: FollowersSyncCacheMockSetDigestExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSetDigest.expectations = append(mmSetDigest.expectations, expectation)
	return expectation
}

// Then sets up FollowersSyncCache.SetDigest return parameters for the expectation previously defined by the When method

func (e *FollowersSyncCacheMockSetDigestExpectation) Then() *FollowersSyncCacheMock {
	return e.mock
}

// Times sets number of times FollowersSyncCache.SetDigest should be invoked
func (mmSetDigest *mFollowersSyncCacheMockSetDigest) Times(n uint64) *mFollowersSyncCacheMockSetDigest {
	if n == 0 {
		mmSetDigest.mock.t.Fatalf("Times of FollowersSyncCacheMock.SetDigest mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSetDigest.expectedInvocations, n)
	mmSetDigest.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSetDigest
}

func (mmSetDigest *mFollowersSyncCacheMockSetDigest) invocationsDone() bool {
	if len(mmSetDigest.expectations) == 0 && mmSetDigest.defaultExpectation == nil && mmSetDigest.mock.funcSetDigest == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSetDigest.mock.afterSetDigestCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSetDigest.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SetDigest implements mm_port.FollowersSyncCache
func (mmSetDigest *FollowersSyncCacheMock) SetDigest(ctx context.Context, actorIRI string, targetDomain string, digest string) {
	mm_atomic.AddUint64(&mmSetDigest.beforeSetDigestCounter, 1)
	defer mm_atomic.AddUint64(&mmSetDigest.afterSetDigestCounter, 1)

	mmSetDigest.t.Helper()

	if mmSetDigest.inspectFuncSetDigest != nil {
		mmSetDigest.inspectFuncSetDigest(ctx, actorIRI, targetDomain, digest)
	}

	mm_params := FollowersSyncCacheMockSetDigestParams{ctx, actorIRI, targetDomain, digest}

	// Record call args
	mmSetDigest.SetDigestMock.mutex.Lock()
	mmSetDigest.SetDigestMock.callArgs = append(mmSetDigest.SetDigestMock.callArgs, &mm_params)
	mmSetDigest.SetDigestMock.mutex.Unlock()

	for _, e := range mmSetDigest.SetDigestMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return
		}
	}

	if mmSetDigest.SetDigestMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSetDigest.SetDigestMock.defaultExpectation.Counter, 1)
		mm_want := mmSetDigest.SetDigestMock.defaultExpectation.params
		mm_want_ptrs := mmSetDigest.SetDigestMock.defaultExpectation.paramPtrs

		mm_got := FollowersSyncCacheMockSetDigestParams{ctx, actorIRI, targetDomain, digest}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSetDigest.t.Errorf("FollowersSyncCacheMock.SetDigest got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSetDigest.SetDigestMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.actorIRI != nil && !minimock.Equal(*mm_want_ptrs.actorIRI, mm_got.actorIRI) {
				mmSetDigest.t.Errorf("FollowersSyncCacheMock.SetDigest got unexpected parameter actorIRI, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSetDigest.SetDigestMock.defaultExpectation.expectationOrigins.originActorIRI, *mm_want_ptrs.actorIRI, mm_got.actorIRI, minimock.Diff(*mm_want_ptrs.actorIRI, mm_got.actorIRI))
			}

			if mm_want_ptrs.targetDomain != nil && !minimock.Equal(*mm_want_ptrs.targetDomain, mm_got.targetDomain) {
				mmSetDigest.t.Errorf("FollowersSyncCacheMock.SetDigest got unexpected parameter targetDomain, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSetDigest.SetDigestMock.defaultExpectation.expectationOrigins.originTargetDomain, *mm_want_ptrs.targetDomain, mm_got.targetDomain, minimock.Diff(*mm_want_ptrs.targetDomain, mm_got.targetDomain))
			}

			if mm_want_ptrs.digest != nil && !minimock.Equal(*mm_want_ptrs.digest, mm_got.digest) {
				mmSetDigest.t.Errorf("FollowersSyncCacheMock.SetDigest got unexpected parameter digest, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSetDigest.SetDigestMock.defaultExpectation.expectationOrigins.originDigest, *mm_want_ptrs.digest, mm_got.digest, minimock.Diff(*mm_want_ptrs.digest, mm_got.digest))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSetDigest.t.Errorf("FollowersSyncCacheMock.SetDigest got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSetDigest.SetDigestMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		return

	}
	if mmSetDigest.funcSetDigest != nil {
		mmSetDigest.funcSetDigest(ctx, actorIRI, targetDomain, digest)
		return
	}
	mmSetDigest.t.Fatalf("Unexpected call to FollowersSyncCacheMock.SetDigest. %v %v %v %v", ctx, actorIRI, targetDomain, digest)

}

// SetDigestAfterCounter returns a count of finished FollowersSyncCacheMock.SetDigest invocations
func (mmSetDigest *FollowersSyncCacheMock) SetDigestAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSetDigest.afterSetDigestCounter)
}

// SetDigestBeforeCounter returns a count of FollowersSyncCacheMock.SetDigest invocations
func (mmSetDigest *FollowersSyncCacheMock) SetDigestBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSetDigest.beforeSetDigestCounter)
}

// Calls returns a list of arguments used in each call to FollowersSyncCacheMock.SetDigest.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSetDigest *mFollowersSyncCacheMockSetDigest) Calls() []*FollowersSyncCacheMockSetDigestParams {
	mmSetDigest.mutex.RLock()

	argCopy := make([]*FollowersSyncCacheMockSetDigestParams, len(mmSetDigest.callArgs))
	copy(argCopy, mmSetDigest.callArgs)

	mmSetDigest.mutex.RUnlock()

	return argCopy
}

// MinimockSetDigestDone returns true if the count of the SetDigest invocations corresponds
// the number of defined expectations
func (m *FollowersSyncCacheMock) MinimockSetDigestDone() bool {
	if m.SetDigestMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SetDigestMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SetDigestMock.invocationsDone()
}

// MinimockSetDigestInspect logs each unmet expectation
func (m *FollowersSyncCacheMock) MinimockSetDigestInspect() {
	for _, e := range m.SetDigestMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to FollowersSyncCacheMock.SetDigest at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSetDigestCounter := mm_atomic.LoadUint64(&m.afterSetDigestCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SetDigestMock.defaultExpectation != nil && afterSetDigestCounter < 1 {
		if m.SetDigestMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to FollowersSyncCacheMock.SetDigest at\n%s", m.SetDigestMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to FollowersSyncCacheMock.SetDigest at\n%s with params: %#v", m.SetDigestMock.defaultExpectation.expectationOrigins.origin, *m.SetDigestMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSetDigest != nil && afterSetDigestCounter < 1 {
		m.t.Errorf("Expected call to FollowersSyncCacheMock.SetDigest at\n%s", m.funcSetDigestOrigin)
	}

	if !m.SetDigestMock.invocationsDone() && afterSetDigestCounter > 0 {
		m.t.Errorf("Expected %d calls to FollowersSyncCacheMock.SetDigest at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SetDigestMock.expectedInvocations), m.SetDigestMock.expectedInvocationsOrigin, afterSetDigestCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *FollowersSyncCacheMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockEvictDigestInspect()

			m.MinimockGetDigestInspect()

			m.MinimockSetDigestInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *FollowersSyncCacheMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *FollowersSyncCacheMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockEvictDigestDone() &&
		m.MinimockGetDigestDone() &&
		m.MinimockSetDigestDone()
}
