// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package portmock

//go:generate minimock -i sprezz/internal/domain/port.GraphVersionWriter -o graph_version_writer_mock.go -n GraphVersionWriterMock -p portmock

import (
	"context"
	"sprezz/internal/domain/model"
	mm_port "sprezz/internal/domain/port"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// GraphVersionWriterMock implements mm_port.GraphVersionWriter
type GraphVersionWriterMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcSaveGraphVersion          func(ctx context.Context, activityIRI string, objectIRI string, payload []byte, quads []model.Quad) (err error)
	funcSaveGraphVersionOrigin    string
	inspectFuncSaveGraphVersion   func(ctx context.Context, activityIRI string, objectIRI string, payload []byte, quads []model.Quad)
	afterSaveGraphVersionCounter  uint64
	beforeSaveGraphVersionCounter uint64
	SaveGraphVersionMock          mGraphVersionWriterMockSaveGraphVersion

	funcSaveGraphVersionWithMedia          func(ctx context.Context, params mm_port.MediaAttachmentParams) (err error)
	funcSaveGraphVersionWithMediaOrigin    string
	inspectFuncSaveGraphVersionWithMedia   func(ctx context.Context, params mm_port.MediaAttachmentParams)
	afterSaveGraphVersionWithMediaCounter  uint64
	beforeSaveGraphVersionWithMediaCounter uint64
	SaveGraphVersionWithMediaMock          mGraphVersionWriterMockSaveGraphVersionWithMedia
}

// NewGraphVersionWriterMock returns a mock for mm_port.GraphVersionWriter
func NewGraphVersionWriterMock(t minimock.Tester) *GraphVersionWriterMock {
	m := &GraphVersionWriterMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.SaveGraphVersionMock = mGraphVersionWriterMockSaveGraphVersion{mock: m}
	m.SaveGraphVersionMock.callArgs = []*GraphVersionWriterMockSaveGraphVersionParams{}

	m.SaveGraphVersionWithMediaMock = mGraphVersionWriterMockSaveGraphVersionWithMedia{mock: m}
	m.SaveGraphVersionWithMediaMock.callArgs = []*GraphVersionWriterMockSaveGraphVersionWithMediaParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mGraphVersionWriterMockSaveGraphVersion struct {
	optional           bool
	mock               *GraphVersionWriterMock
	defaultExpectation *GraphVersionWriterMockSaveGraphVersionExpectation
	expectations       []*GraphVersionWriterMockSaveGraphVersionExpectation

	callArgs []*GraphVersionWriterMockSaveGraphVersionParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// GraphVersionWriterMockSaveGraphVersionExpectation specifies expectation struct of the GraphVersionWriter.SaveGraphVersion
type GraphVersionWriterMockSaveGraphVersionExpectation struct {
	mock               *GraphVersionWriterMock
	params             *GraphVersionWriterMockSaveGraphVersionParams
	paramPtrs          *GraphVersionWriterMockSaveGraphVersionParamPtrs
	expectationOrigins GraphVersionWriterMockSaveGraphVersionExpectationOrigins
	results            *GraphVersionWriterMockSaveGraphVersionResults
	returnOrigin       string
	Counter            uint64
}

// GraphVersionWriterMockSaveGraphVersionParams contains parameters of the GraphVersionWriter.SaveGraphVersion
type GraphVersionWriterMockSaveGraphVersionParams struct {
	ctx         context.Context
	activityIRI string
	objectIRI   string
	payload     []byte
	quads       []model.Quad
}

// GraphVersionWriterMockSaveGraphVersionParamPtrs contains pointers to parameters of the GraphVersionWriter.SaveGraphVersion
type GraphVersionWriterMockSaveGraphVersionParamPtrs struct {
	ctx         *context.Context
	activityIRI *string
	objectIRI   *string
	payload     *[]byte
	quads       *[]model.Quad
}

// GraphVersionWriterMockSaveGraphVersionResults contains results of the GraphVersionWriter.SaveGraphVersion
type GraphVersionWriterMockSaveGraphVersionResults struct {
	err error
}

// GraphVersionWriterMockSaveGraphVersionOrigins contains origins of expectations of the GraphVersionWriter.SaveGraphVersion
type GraphVersionWriterMockSaveGraphVersionExpectationOrigins struct {
	origin            string
	originCtx         string
	originActivityIRI string
	originObjectIRI   string
	originPayload     string
	originQuads       string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSaveGraphVersion *mGraphVersionWriterMockSaveGraphVersion) Optional() *mGraphVersionWriterMockSaveGraphVersion {
	mmSaveGraphVersion.optional = true
	return mmSaveGraphVersion
}

// Expect sets up expected params for GraphVersionWriter.SaveGraphVersion
func (mmSaveGraphVersion *mGraphVersionWriterMockSaveGraphVersion) Expect(ctx context.Context, activityIRI string, objectIRI string, payload []byte, quads []model.Quad) *mGraphVersionWriterMockSaveGraphVersion {
	if mmSaveGraphVersion.mock.funcSaveGraphVersion != nil {
		mmSaveGraphVersion.mock.t.Fatalf("GraphVersionWriterMock.SaveGraphVersion mock is already set by Set")
	}

	if mmSaveGraphVersion.defaultExpectation == nil {
		mmSaveGraphVersion.defaultExpectation = &GraphVersionWriterMockSaveGraphVersionExpectation{}
	}

	if mmSaveGraphVersion.defaultExpectation.paramPtrs != nil {
		mmSaveGraphVersion.mock.t.Fatalf("GraphVersionWriterMock.SaveGraphVersion mock is already set by ExpectParams functions")
	}

	mmSaveGraphVersion.defaultExpectation.params = &GraphVersionWriterMockSaveGraphVersionParams{ctx, activityIRI, objectIRI, payload, quads}
	mmSaveGraphVersion.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSaveGraphVersion.expectations {
		if minimock.Equal(e.params, mmSaveGraphVersion.defaultExpectation.params) {
			mmSaveGraphVersion.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSaveGraphVersion.defaultExpectation.params)
		}
	}

	return mmSaveGraphVersion
}

// ExpectCtxParam1 sets up expected param ctx for GraphVersionWriter.SaveGraphVersion
func (mmSaveGraphVersion *mGraphVersionWriterMockSaveGraphVersion) ExpectCtxParam1(ctx context.Context) *mGraphVersionWriterMockSaveGraphVersion {
	if mmSaveGraphVersion.mock.funcSaveGraphVersion != nil {
		mmSaveGraphVersion.mock.t.Fatalf("GraphVersionWriterMock.SaveGraphVersion mock is already set by Set")
	}

	if mmSaveGraphVersion.defaultExpectation == nil {
		mmSaveGraphVersion.defaultExpectation = &GraphVersionWriterMockSaveGraphVersionExpectation{}
	}

	if mmSaveGraphVersion.defaultExpectation.params != nil {
		mmSaveGraphVersion.mock.t.Fatalf("GraphVersionWriterMock.SaveGraphVersion mock is already set by Expect")
	}

	if mmSaveGraphVersion.defaultExpectation.paramPtrs == nil {
		mmSaveGraphVersion.defaultExpectation.paramPtrs = &GraphVersionWriterMockSaveGraphVersionParamPtrs{}
	}
	mmSaveGraphVersion.defaultExpectation.paramPtrs.ctx = &ctx
	mmSaveGraphVersion.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSaveGraphVersion
}

// ExpectActivityIRIParam2 sets up expected param activityIRI for GraphVersionWriter.SaveGraphVersion
func (mmSaveGraphVersion *mGraphVersionWriterMockSaveGraphVersion) ExpectActivityIRIParam2(activityIRI string) *mGraphVersionWriterMockSaveGraphVersion {
	if mmSaveGraphVersion.mock.funcSaveGraphVersion != nil {
		mmSaveGraphVersion.mock.t.Fatalf("GraphVersionWriterMock.SaveGraphVersion mock is already set by Set")
	}

	if mmSaveGraphVersion.defaultExpectation == nil {
		mmSaveGraphVersion.defaultExpectation = &GraphVersionWriterMockSaveGraphVersionExpectation{}
	}

	if mmSaveGraphVersion.defaultExpectation.params != nil {
		mmSaveGraphVersion.mock.t.Fatalf("GraphVersionWriterMock.SaveGraphVersion mock is already set by Expect")
	}

	if mmSaveGraphVersion.defaultExpectation.paramPtrs == nil {
		mmSaveGraphVersion.defaultExpectation.paramPtrs = &GraphVersionWriterMockSaveGraphVersionParamPtrs{}
	}
	mmSaveGraphVersion.defaultExpectation.paramPtrs.activityIRI = &activityIRI
	mmSaveGraphVersion.defaultExpectation.expectationOrigins.originActivityIRI = minimock.CallerInfo(1)

	return mmSaveGraphVersion
}

// ExpectObjectIRIParam3 sets up expected param objectIRI for GraphVersionWriter.SaveGraphVersion
func (mmSaveGraphVersion *mGraphVersionWriterMockSaveGraphVersion) ExpectObjectIRIParam3(objectIRI string) *mGraphVersionWriterMockSaveGraphVersion {
	if mmSaveGraphVersion.mock.funcSaveGraphVersion != nil {
		mmSaveGraphVersion.mock.t.Fatalf("GraphVersionWriterMock.SaveGraphVersion mock is already set by Set")
	}

	if mmSaveGraphVersion.defaultExpectation == nil {
		mmSaveGraphVersion.defaultExpectation = &GraphVersionWriterMockSaveGraphVersionExpectation{}
	}

	if mmSaveGraphVersion.defaultExpectation.params != nil {
		mmSaveGraphVersion.mock.t.Fatalf("GraphVersionWriterMock.SaveGraphVersion mock is already set by Expect")
	}

	if mmSaveGraphVersion.defaultExpectation.paramPtrs == nil {
		mmSaveGraphVersion.defaultExpectation.paramPtrs = &GraphVersionWriterMockSaveGraphVersionParamPtrs{}
	}
	mmSaveGraphVersion.defaultExpectation.paramPtrs.objectIRI = &objectIRI
	mmSaveGraphVersion.defaultExpectation.expectationOrigins.originObjectIRI = minimock.CallerInfo(1)

	return mmSaveGraphVersion
}

// ExpectPayloadParam4 sets up expected param payload for GraphVersionWriter.SaveGraphVersion
func (mmSaveGraphVersion *mGraphVersionWriterMockSaveGraphVersion) ExpectPayloadParam4(payload []byte) *mGraphVersionWriterMockSaveGraphVersion {
	if mmSaveGraphVersion.mock.funcSaveGraphVersion != nil {
		mmSaveGraphVersion.mock.t.Fatalf("GraphVersionWriterMock.SaveGraphVersion mock is already set by Set")
	}

	if mmSaveGraphVersion.defaultExpectation == nil {
		mmSaveGraphVersion.defaultExpectation = &GraphVersionWriterMockSaveGraphVersionExpectation{}
	}

	if mmSaveGraphVersion.defaultExpectation.params != nil {
		mmSaveGraphVersion.mock.t.Fatalf("GraphVersionWriterMock.SaveGraphVersion mock is already set by Expect")
	}

	if mmSaveGraphVersion.defaultExpectation.paramPtrs == nil {
		mmSaveGraphVersion.defaultExpectation.paramPtrs = &GraphVersionWriterMockSaveGraphVersionParamPtrs{}
	}
	mmSaveGraphVersion.defaultExpectation.paramPtrs.payload = &payload
	mmSaveGraphVersion.defaultExpectation.expectationOrigins.originPayload = minimock.CallerInfo(1)

	return mmSaveGraphVersion
}

// ExpectQuadsParam5 sets up expected param quads for GraphVersionWriter.SaveGraphVersion
func (mmSaveGraphVersion *mGraphVersionWriterMockSaveGraphVersion) ExpectQuadsParam5(quads []model.Quad) *mGraphVersionWriterMockSaveGraphVersion {
	if mmSaveGraphVersion.mock.funcSaveGraphVersion != nil {
		mmSaveGraphVersion.mock.t.Fatalf("GraphVersionWriterMock.SaveGraphVersion mock is already set by Set")
	}

	if mmSaveGraphVersion.defaultExpectation == nil {
		mmSaveGraphVersion.defaultExpectation = &GraphVersionWriterMockSaveGraphVersionExpectation{}
	}

	if mmSaveGraphVersion.defaultExpectation.params != nil {
		mmSaveGraphVersion.mock.t.Fatalf("GraphVersionWriterMock.SaveGraphVersion mock is already set by Expect")
	}

	if mmSaveGraphVersion.defaultExpectation.paramPtrs == nil {
		mmSaveGraphVersion.defaultExpectation.paramPtrs = &GraphVersionWriterMockSaveGraphVersionParamPtrs{}
	}
	mmSaveGraphVersion.defaultExpectation.paramPtrs.quads = &quads
	mmSaveGraphVersion.defaultExpectation.expectationOrigins.originQuads = minimock.CallerInfo(1)

	return mmSaveGraphVersion
}

// Inspect accepts an inspector function that has same arguments as the GraphVersionWriter.SaveGraphVersion
func (mmSaveGraphVersion *mGraphVersionWriterMockSaveGraphVersion) Inspect(f func(ctx context.Context, activityIRI string, objectIRI string, payload []byte, quads []model.Quad)) *mGraphVersionWriterMockSaveGraphVersion {
	if mmSaveGraphVersion.mock.inspectFuncSaveGraphVersion != nil {
		mmSaveGraphVersion.mock.t.Fatalf("Inspect function is already set for GraphVersionWriterMock.SaveGraphVersion")
	}

	mmSaveGraphVersion.mock.inspectFuncSaveGraphVersion = f

	return mmSaveGraphVersion
}

// Return sets up results that will be returned by GraphVersionWriter.SaveGraphVersion
func (mmSaveGraphVersion *mGraphVersionWriterMockSaveGraphVersion) Return(err error) *GraphVersionWriterMock {
	if mmSaveGraphVersion.mock.funcSaveGraphVersion != nil {
		mmSaveGraphVersion.mock.t.Fatalf("GraphVersionWriterMock.SaveGraphVersion mock is already set by Set")
	}

	if mmSaveGraphVersion.defaultExpectation == nil {
		mmSaveGraphVersion.defaultExpectation = &GraphVersionWriterMockSaveGraphVersionExpectation{mock: mmSaveGraphVersion.mock}
	}
	mmSaveGraphVersion.defaultExpectation.results = &GraphVersionWriterMockSaveGraphVersionResults{err}
	mmSaveGraphVersion.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSaveGraphVersion.mock
}

// Set uses given function f to mock the GraphVersionWriter.SaveGraphVersion method
func (mmSaveGraphVersion *mGraphVersionWriterMockSaveGraphVersion) Set(f func(ctx context.Context, activityIRI string, objectIRI string, payload []byte, quads []model.Quad) (err error)) *GraphVersionWriterMock {
	if mmSaveGraphVersion.defaultExpectation != nil {
		mmSaveGraphVersion.mock.t.Fatalf("Default expectation is already set for the GraphVersionWriter.SaveGraphVersion method")
	}

	if len(mmSaveGraphVersion.expectations) > 0 {
		mmSaveGraphVersion.mock.t.Fatalf("Some expectations are already set for the GraphVersionWriter.SaveGraphVersion method")
	}

	mmSaveGraphVersion.mock.funcSaveGraphVersion = f
	mmSaveGraphVersion.mock.funcSaveGraphVersionOrigin = minimock.CallerInfo(1)
	return mmSaveGraphVersion.mock
}

// When sets expectation for the GraphVersionWriter.SaveGraphVersion which will trigger the result defined by the following
// Then helper
func (mmSaveGraphVersion *mGraphVersionWriterMockSaveGraphVersion) When(ctx context.Context, activityIRI string, objectIRI string, payload []byte, quads []model.Quad) *GraphVersionWriterMockSaveGraphVersionExpectation {
	if mmSaveGraphVersion.mock.funcSaveGraphVersion != nil {
		mmSaveGraphVersion.mock.t.Fatalf("GraphVersionWriterMock.SaveGraphVersion mock is already set by Set")
	}

	expectation := &GraphVersionWriterMockSaveGraphVersionExpectation{
		mock:               mmSaveGraphVersion.mock,
		params:             &GraphVersionWriterMockSaveGraphVersionParams{ctx, activityIRI, objectIRI, payload, quads},
		expectationOrigins: GraphVersionWriterMockSaveGraphVersionExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSaveGraphVersion.expectations = append(mmSaveGraphVersion.expectations, expectation)
	return expectation
}

// Then sets up GraphVersionWriter.SaveGraphVersion return parameters for the expectation previously defined by the When method
func (e *GraphVersionWriterMockSaveGraphVersionExpectation) Then(err error) *GraphVersionWriterMock {
	e.results = &GraphVersionWriterMockSaveGraphVersionResults{err}
	return e.mock
}

// Times sets number of times GraphVersionWriter.SaveGraphVersion should be invoked
func (mmSaveGraphVersion *mGraphVersionWriterMockSaveGraphVersion) Times(n uint64) *mGraphVersionWriterMockSaveGraphVersion {
	if n == 0 {
		mmSaveGraphVersion.mock.t.Fatalf("Times of GraphVersionWriterMock.SaveGraphVersion mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSaveGraphVersion.expectedInvocations, n)
	mmSaveGraphVersion.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSaveGraphVersion
}

func (mmSaveGraphVersion *mGraphVersionWriterMockSaveGraphVersion) invocationsDone() bool {
	if len(mmSaveGraphVersion.expectations) == 0 && mmSaveGraphVersion.defaultExpectation == nil && mmSaveGraphVersion.mock.funcSaveGraphVersion == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSaveGraphVersion.mock.afterSaveGraphVersionCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSaveGraphVersion.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SaveGraphVersion implements mm_port.GraphVersionWriter
func (mmSaveGraphVersion *GraphVersionWriterMock) SaveGraphVersion(ctx context.Context, activityIRI string, objectIRI string, payload []byte, quads []model.Quad) (err error) {
	mm_atomic.AddUint64(&mmSaveGraphVersion.beforeSaveGraphVersionCounter, 1)
	defer mm_atomic.AddUint64(&mmSaveGraphVersion.afterSaveGraphVersionCounter, 1)

	mmSaveGraphVersion.t.Helper()

	if mmSaveGraphVersion.inspectFuncSaveGraphVersion != nil {
		mmSaveGraphVersion.inspectFuncSaveGraphVersion(ctx, activityIRI, objectIRI, payload, quads)
	}

	mm_params := GraphVersionWriterMockSaveGraphVersionParams{ctx, activityIRI, objectIRI, payload, quads}

	// Record call args
	mmSaveGraphVersion.SaveGraphVersionMock.mutex.Lock()
	mmSaveGraphVersion.SaveGraphVersionMock.callArgs = append(mmSaveGraphVersion.SaveGraphVersionMock.callArgs, &mm_params)
	mmSaveGraphVersion.SaveGraphVersionMock.mutex.Unlock()

	for _, e := range mmSaveGraphVersion.SaveGraphVersionMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSaveGraphVersion.SaveGraphVersionMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSaveGraphVersion.SaveGraphVersionMock.defaultExpectation.Counter, 1)
		mm_want := mmSaveGraphVersion.SaveGraphVersionMock.defaultExpectation.params
		mm_want_ptrs := mmSaveGraphVersion.SaveGraphVersionMock.defaultExpectation.paramPtrs

		mm_got := GraphVersionWriterMockSaveGraphVersionParams{ctx, activityIRI, objectIRI, payload, quads}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSaveGraphVersion.t.Errorf("GraphVersionWriterMock.SaveGraphVersion got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSaveGraphVersion.SaveGraphVersionMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.activityIRI != nil && !minimock.Equal(*mm_want_ptrs.activityIRI, mm_got.activityIRI) {
				mmSaveGraphVersion.t.Errorf("GraphVersionWriterMock.SaveGraphVersion got unexpected parameter activityIRI, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSaveGraphVersion.SaveGraphVersionMock.defaultExpectation.expectationOrigins.originActivityIRI, *mm_want_ptrs.activityIRI, mm_got.activityIRI, minimock.Diff(*mm_want_ptrs.activityIRI, mm_got.activityIRI))
			}

			if mm_want_ptrs.objectIRI != nil && !minimock.Equal(*mm_want_ptrs.objectIRI, mm_got.objectIRI) {
				mmSaveGraphVersion.t.Errorf("GraphVersionWriterMock.SaveGraphVersion got unexpected parameter objectIRI, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSaveGraphVersion.SaveGraphVersionMock.defaultExpectation.expectationOrigins.originObjectIRI, *mm_want_ptrs.objectIRI, mm_got.objectIRI, minimock.Diff(*mm_want_ptrs.objectIRI, mm_got.objectIRI))
			}

			if mm_want_ptrs.payload != nil && !minimock.Equal(*mm_want_ptrs.payload, mm_got.payload) {
				mmSaveGraphVersion.t.Errorf("GraphVersionWriterMock.SaveGraphVersion got unexpected parameter payload, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSaveGraphVersion.SaveGraphVersionMock.defaultExpectation.expectationOrigins.originPayload, *mm_want_ptrs.payload, mm_got.payload, minimock.Diff(*mm_want_ptrs.payload, mm_got.payload))
			}

			if mm_want_ptrs.quads != nil && !minimock.Equal(*mm_want_ptrs.quads, mm_got.quads) {
				mmSaveGraphVersion.t.Errorf("GraphVersionWriterMock.SaveGraphVersion got unexpected parameter quads, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSaveGraphVersion.SaveGraphVersionMock.defaultExpectation.expectationOrigins.originQuads, *mm_want_ptrs.quads, mm_got.quads, minimock.Diff(*mm_want_ptrs.quads, mm_got.quads))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSaveGraphVersion.t.Errorf("GraphVersionWriterMock.SaveGraphVersion got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSaveGraphVersion.SaveGraphVersionMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSaveGraphVersion.SaveGraphVersionMock.defaultExpectation.results
		if mm_results == nil {
			mmSaveGraphVersion.t.Fatal("No results are set for the GraphVersionWriterMock.SaveGraphVersion")
		}
		return (*mm_results).err
	}
	if mmSaveGraphVersion.funcSaveGraphVersion != nil {
		return mmSaveGraphVersion.funcSaveGraphVersion(ctx, activityIRI, objectIRI, payload, quads)
	}
	mmSaveGraphVersion.t.Fatalf("Unexpected call to GraphVersionWriterMock.SaveGraphVersion. %v %v %v %v %v", ctx, activityIRI, objectIRI, payload, quads)
	return
}

// SaveGraphVersionAfterCounter returns a count of finished GraphVersionWriterMock.SaveGraphVersion invocations
func (mmSaveGraphVersion *GraphVersionWriterMock) SaveGraphVersionAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSaveGraphVersion.afterSaveGraphVersionCounter)
}

// SaveGraphVersionBeforeCounter returns a count of GraphVersionWriterMock.SaveGraphVersion invocations
func (mmSaveGraphVersion *GraphVersionWriterMock) SaveGraphVersionBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSaveGraphVersion.beforeSaveGraphVersionCounter)
}

// Calls returns a list of arguments used in each call to GraphVersionWriterMock.SaveGraphVersion.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSaveGraphVersion *mGraphVersionWriterMockSaveGraphVersion) Calls() []*GraphVersionWriterMockSaveGraphVersionParams {
	mmSaveGraphVersion.mutex.RLock()

	argCopy := make([]*GraphVersionWriterMockSaveGraphVersionParams, len(mmSaveGraphVersion.callArgs))
	copy(argCopy, mmSaveGraphVersion.callArgs)

	mmSaveGraphVersion.mutex.RUnlock()

	return argCopy
}

// MinimockSaveGraphVersionDone returns true if the count of the SaveGraphVersion invocations corresponds
// the number of defined expectations
func (m *GraphVersionWriterMock) MinimockSaveGraphVersionDone() bool {
	if m.SaveGraphVersionMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SaveGraphVersionMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SaveGraphVersionMock.invocationsDone()
}

// MinimockSaveGraphVersionInspect logs each unmet expectation
func (m *GraphVersionWriterMock) MinimockSaveGraphVersionInspect() {
	for _, e := range m.SaveGraphVersionMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to GraphVersionWriterMock.SaveGraphVersion at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSaveGraphVersionCounter := mm_atomic.LoadUint64(&m.afterSaveGraphVersionCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SaveGraphVersionMock.defaultExpectation != nil && afterSaveGraphVersionCounter < 1 {
		if m.SaveGraphVersionMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to GraphVersionWriterMock.SaveGraphVersion at\n%s", m.SaveGraphVersionMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to GraphVersionWriterMock.SaveGraphVersion at\n%s with params: %#v", m.SaveGraphVersionMock.defaultExpectation.expectationOrigins.origin, *m.SaveGraphVersionMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSaveGraphVersion != nil && afterSaveGraphVersionCounter < 1 {
		m.t.Errorf("Expected call to GraphVersionWriterMock.SaveGraphVersion at\n%s", m.funcSaveGraphVersionOrigin)
	}

	if !m.SaveGraphVersionMock.invocationsDone() && afterSaveGraphVersionCounter > 0 {
		m.t.Errorf("Expected %d calls to GraphVersionWriterMock.SaveGraphVersion at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SaveGraphVersionMock.expectedInvocations), m.SaveGraphVersionMock.expectedInvocationsOrigin, afterSaveGraphVersionCounter)
	}
}

type mGraphVersionWriterMockSaveGraphVersionWithMedia struct {
	optional           bool
	mock               *GraphVersionWriterMock
	defaultExpectation *GraphVersionWriterMockSaveGraphVersionWithMediaExpectation
	expectations       []*GraphVersionWriterMockSaveGraphVersionWithMediaExpectation

	callArgs []*GraphVersionWriterMockSaveGraphVersionWithMediaParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// GraphVersionWriterMockSaveGraphVersionWithMediaExpectation specifies expectation struct of the GraphVersionWriter.SaveGraphVersionWithMedia
type GraphVersionWriterMockSaveGraphVersionWithMediaExpectation struct {
	mock               *GraphVersionWriterMock
	params             *GraphVersionWriterMockSaveGraphVersionWithMediaParams
	paramPtrs          *GraphVersionWriterMockSaveGraphVersionWithMediaParamPtrs
	expectationOrigins GraphVersionWriterMockSaveGraphVersionWithMediaExpectationOrigins
	results            *GraphVersionWriterMockSaveGraphVersionWithMediaResults
	returnOrigin       string
	Counter            uint64
}

// GraphVersionWriterMockSaveGraphVersionWithMediaParams contains parameters of the GraphVersionWriter.SaveGraphVersionWithMedia
type GraphVersionWriterMockSaveGraphVersionWithMediaParams struct {
	ctx    context.Context
	params mm_port.MediaAttachmentParams
}

// GraphVersionWriterMockSaveGraphVersionWithMediaParamPtrs contains pointers to parameters of the GraphVersionWriter.SaveGraphVersionWithMedia
type GraphVersionWriterMockSaveGraphVersionWithMediaParamPtrs struct {
	ctx    *context.Context
	params *mm_port.MediaAttachmentParams
}

// GraphVersionWriterMockSaveGraphVersionWithMediaResults contains results of the GraphVersionWriter.SaveGraphVersionWithMedia
type GraphVersionWriterMockSaveGraphVersionWithMediaResults struct {
	err error
}

// GraphVersionWriterMockSaveGraphVersionWithMediaOrigins contains origins of expectations of the GraphVersionWriter.SaveGraphVersionWithMedia
type GraphVersionWriterMockSaveGraphVersionWithMediaExpectationOrigins struct {
	origin       string
	originCtx    string
	originParams string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSaveGraphVersionWithMedia *mGraphVersionWriterMockSaveGraphVersionWithMedia) Optional() *mGraphVersionWriterMockSaveGraphVersionWithMedia {
	mmSaveGraphVersionWithMedia.optional = true
	return mmSaveGraphVersionWithMedia
}

// Expect sets up expected params for GraphVersionWriter.SaveGraphVersionWithMedia
func (mmSaveGraphVersionWithMedia *mGraphVersionWriterMockSaveGraphVersionWithMedia) Expect(ctx context.Context, params mm_port.MediaAttachmentParams) *mGraphVersionWriterMockSaveGraphVersionWithMedia {
	if mmSaveGraphVersionWithMedia.mock.funcSaveGraphVersionWithMedia != nil {
		mmSaveGraphVersionWithMedia.mock.t.Fatalf("GraphVersionWriterMock.SaveGraphVersionWithMedia mock is already set by Set")
	}

	if mmSaveGraphVersionWithMedia.defaultExpectation == nil {
		mmSaveGraphVersionWithMedia.defaultExpectation = &GraphVersionWriterMockSaveGraphVersionWithMediaExpectation{}
	}

	if mmSaveGraphVersionWithMedia.defaultExpectation.paramPtrs != nil {
		mmSaveGraphVersionWithMedia.mock.t.Fatalf("GraphVersionWriterMock.SaveGraphVersionWithMedia mock is already set by ExpectParams functions")
	}

	mmSaveGraphVersionWithMedia.defaultExpectation.params = &GraphVersionWriterMockSaveGraphVersionWithMediaParams{ctx, params}
	mmSaveGraphVersionWithMedia.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSaveGraphVersionWithMedia.expectations {
		if minimock.Equal(e.params, mmSaveGraphVersionWithMedia.defaultExpectation.params) {
			mmSaveGraphVersionWithMedia.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSaveGraphVersionWithMedia.defaultExpectation.params)
		}
	}

	return mmSaveGraphVersionWithMedia
}

// ExpectCtxParam1 sets up expected param ctx for GraphVersionWriter.SaveGraphVersionWithMedia
func (mmSaveGraphVersionWithMedia *mGraphVersionWriterMockSaveGraphVersionWithMedia) ExpectCtxParam1(ctx context.Context) *mGraphVersionWriterMockSaveGraphVersionWithMedia {
	if mmSaveGraphVersionWithMedia.mock.funcSaveGraphVersionWithMedia != nil {
		mmSaveGraphVersionWithMedia.mock.t.Fatalf("GraphVersionWriterMock.SaveGraphVersionWithMedia mock is already set by Set")
	}

	if mmSaveGraphVersionWithMedia.defaultExpectation == nil {
		mmSaveGraphVersionWithMedia.defaultExpectation = &GraphVersionWriterMockSaveGraphVersionWithMediaExpectation{}
	}

	if mmSaveGraphVersionWithMedia.defaultExpectation.params != nil {
		mmSaveGraphVersionWithMedia.mock.t.Fatalf("GraphVersionWriterMock.SaveGraphVersionWithMedia mock is already set by Expect")
	}

	if mmSaveGraphVersionWithMedia.defaultExpectation.paramPtrs == nil {
		mmSaveGraphVersionWithMedia.defaultExpectation.paramPtrs = &GraphVersionWriterMockSaveGraphVersionWithMediaParamPtrs{}
	}
	mmSaveGraphVersionWithMedia.defaultExpectation.paramPtrs.ctx = &ctx
	mmSaveGraphVersionWithMedia.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSaveGraphVersionWithMedia
}

// ExpectParamsParam2 sets up expected param params for GraphVersionWriter.SaveGraphVersionWithMedia
func (mmSaveGraphVersionWithMedia *mGraphVersionWriterMockSaveGraphVersionWithMedia) ExpectParamsParam2(params mm_port.MediaAttachmentParams) *mGraphVersionWriterMockSaveGraphVersionWithMedia {
	if mmSaveGraphVersionWithMedia.mock.funcSaveGraphVersionWithMedia != nil {
		mmSaveGraphVersionWithMedia.mock.t.Fatalf("GraphVersionWriterMock.SaveGraphVersionWithMedia mock is already set by Set")
	}

	if mmSaveGraphVersionWithMedia.defaultExpectation == nil {
		mmSaveGraphVersionWithMedia.defaultExpectation = &GraphVersionWriterMockSaveGraphVersionWithMediaExpectation{}
	}

	if mmSaveGraphVersionWithMedia.defaultExpectation.params != nil {
		mmSaveGraphVersionWithMedia.mock.t.Fatalf("GraphVersionWriterMock.SaveGraphVersionWithMedia mock is already set by Expect")
	}

	if mmSaveGraphVersionWithMedia.defaultExpectation.paramPtrs == nil {
		mmSaveGraphVersionWithMedia.defaultExpectation.paramPtrs = &GraphVersionWriterMockSaveGraphVersionWithMediaParamPtrs{}
	}
	mmSaveGraphVersionWithMedia.defaultExpectation.paramPtrs.params = &params
	mmSaveGraphVersionWithMedia.defaultExpectation.expectationOrigins.originParams = minimock.CallerInfo(1)

	return mmSaveGraphVersionWithMedia
}

// Inspect accepts an inspector function that has same arguments as the GraphVersionWriter.SaveGraphVersionWithMedia
func (mmSaveGraphVersionWithMedia *mGraphVersionWriterMockSaveGraphVersionWithMedia) Inspect(f func(ctx context.Context, params mm_port.MediaAttachmentParams)) *mGraphVersionWriterMockSaveGraphVersionWithMedia {
	if mmSaveGraphVersionWithMedia.mock.inspectFuncSaveGraphVersionWithMedia != nil {
		mmSaveGraphVersionWithMedia.mock.t.Fatalf("Inspect function is already set for GraphVersionWriterMock.SaveGraphVersionWithMedia")
	}

	mmSaveGraphVersionWithMedia.mock.inspectFuncSaveGraphVersionWithMedia = f

	return mmSaveGraphVersionWithMedia
}

// Return sets up results that will be returned by GraphVersionWriter.SaveGraphVersionWithMedia
func (mmSaveGraphVersionWithMedia *mGraphVersionWriterMockSaveGraphVersionWithMedia) Return(err error) *GraphVersionWriterMock {
	if mmSaveGraphVersionWithMedia.mock.funcSaveGraphVersionWithMedia != nil {
		mmSaveGraphVersionWithMedia.mock.t.Fatalf("GraphVersionWriterMock.SaveGraphVersionWithMedia mock is already set by Set")
	}

	if mmSaveGraphVersionWithMedia.defaultExpectation == nil {
		mmSaveGraphVersionWithMedia.defaultExpectation = &GraphVersionWriterMockSaveGraphVersionWithMediaExpectation{mock: mmSaveGraphVersionWithMedia.mock}
	}
	mmSaveGraphVersionWithMedia.defaultExpectation.results = &GraphVersionWriterMockSaveGraphVersionWithMediaResults{err}
	mmSaveGraphVersionWithMedia.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSaveGraphVersionWithMedia.mock
}

// Set uses given function f to mock the GraphVersionWriter.SaveGraphVersionWithMedia method
func (mmSaveGraphVersionWithMedia *mGraphVersionWriterMockSaveGraphVersionWithMedia) Set(f func(ctx context.Context, params mm_port.MediaAttachmentParams) (err error)) *GraphVersionWriterMock {
	if mmSaveGraphVersionWithMedia.defaultExpectation != nil {
		mmSaveGraphVersionWithMedia.mock.t.Fatalf("Default expectation is already set for the GraphVersionWriter.SaveGraphVersionWithMedia method")
	}

	if len(mmSaveGraphVersionWithMedia.expectations) > 0 {
		mmSaveGraphVersionWithMedia.mock.t.Fatalf("Some expectations are already set for the GraphVersionWriter.SaveGraphVersionWithMedia method")
	}

	mmSaveGraphVersionWithMedia.mock.funcSaveGraphVersionWithMedia = f
	mmSaveGraphVersionWithMedia.mock.funcSaveGraphVersionWithMediaOrigin = minimock.CallerInfo(1)
	return mmSaveGraphVersionWithMedia.mock
}

// When sets expectation for the GraphVersionWriter.SaveGraphVersionWithMedia which will trigger the result defined by the following
// Then helper
func (mmSaveGraphVersionWithMedia *mGraphVersionWriterMockSaveGraphVersionWithMedia) When(ctx context.Context, params mm_port.MediaAttachmentParams) *GraphVersionWriterMockSaveGraphVersionWithMediaExpectation {
	if mmSaveGraphVersionWithMedia.mock.funcSaveGraphVersionWithMedia != nil {
		mmSaveGraphVersionWithMedia.mock.t.Fatalf("GraphVersionWriterMock.SaveGraphVersionWithMedia mock is already set by Set")
	}

	expectation := &GraphVersionWriterMockSaveGraphVersionWithMediaExpectation{
		mock:               mmSaveGraphVersionWithMedia.mock,
		params:             &GraphVersionWriterMockSaveGraphVersionWithMediaParams{ctx, params},
		expectationOrigins: GraphVersionWriterMockSaveGraphVersionWithMediaExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSaveGraphVersionWithMedia.expectations = append(mmSaveGraphVersionWithMedia.expectations, expectation)
	return expectation
}

// Then sets up GraphVersionWriter.SaveGraphVersionWithMedia return parameters for the expectation previously defined by the When method
func (e *GraphVersionWriterMockSaveGraphVersionWithMediaExpectation) Then(err error) *GraphVersionWriterMock {
	e.results = &GraphVersionWriterMockSaveGraphVersionWithMediaResults{err}
	return e.mock
}

// Times sets number of times GraphVersionWriter.SaveGraphVersionWithMedia should be invoked
func (mmSaveGraphVersionWithMedia *mGraphVersionWriterMockSaveGraphVersionWithMedia) Times(n uint64) *mGraphVersionWriterMockSaveGraphVersionWithMedia {
	if n == 0 {
		mmSaveGraphVersionWithMedia.mock.t.Fatalf("Times of GraphVersionWriterMock.SaveGraphVersionWithMedia mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSaveGraphVersionWithMedia.expectedInvocations, n)
	mmSaveGraphVersionWithMedia.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSaveGraphVersionWithMedia
}

func (mmSaveGraphVersionWithMedia *mGraphVersionWriterMockSaveGraphVersionWithMedia) invocationsDone() bool {
	if len(mmSaveGraphVersionWithMedia.expectations) == 0 && mmSaveGraphVersionWithMedia.defaultExpectation == nil && mmSaveGraphVersionWithMedia.mock.funcSaveGraphVersionWithMedia == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSaveGraphVersionWithMedia.mock.afterSaveGraphVersionWithMediaCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSaveGraphVersionWithMedia.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SaveGraphVersionWithMedia implements mm_port.GraphVersionWriter
func (mmSaveGraphVersionWithMedia *GraphVersionWriterMock) SaveGraphVersionWithMedia(ctx context.Context, params mm_port.MediaAttachmentParams) (err error) {
	mm_atomic.AddUint64(&mmSaveGraphVersionWithMedia.beforeSaveGraphVersionWithMediaCounter, 1)
	defer mm_atomic.AddUint64(&mmSaveGraphVersionWithMedia.afterSaveGraphVersionWithMediaCounter, 1)

	mmSaveGraphVersionWithMedia.t.Helper()

	if mmSaveGraphVersionWithMedia.inspectFuncSaveGraphVersionWithMedia != nil {
		mmSaveGraphVersionWithMedia.inspectFuncSaveGraphVersionWithMedia(ctx, params)
	}

	mm_params := GraphVersionWriterMockSaveGraphVersionWithMediaParams{ctx, params}

	// Record call args
	mmSaveGraphVersionWithMedia.SaveGraphVersionWithMediaMock.mutex.Lock()
	mmSaveGraphVersionWithMedia.SaveGraphVersionWithMediaMock.callArgs = append(mmSaveGraphVersionWithMedia.SaveGraphVersionWithMediaMock.callArgs, &mm_params)
	mmSaveGraphVersionWithMedia.SaveGraphVersionWithMediaMock.mutex.Unlock()

	for _, e := range mmSaveGraphVersionWithMedia.SaveGraphVersionWithMediaMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSaveGraphVersionWithMedia.SaveGraphVersionWithMediaMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSaveGraphVersionWithMedia.SaveGraphVersionWithMediaMock.defaultExpectation.Counter, 1)
		mm_want := mmSaveGraphVersionWithMedia.SaveGraphVersionWithMediaMock.defaultExpectation.params
		mm_want_ptrs := mmSaveGraphVersionWithMedia.SaveGraphVersionWithMediaMock.defaultExpectation.paramPtrs

		mm_got := GraphVersionWriterMockSaveGraphVersionWithMediaParams{ctx, params}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSaveGraphVersionWithMedia.t.Errorf("GraphVersionWriterMock.SaveGraphVersionWithMedia got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSaveGraphVersionWithMedia.SaveGraphVersionWithMediaMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.params != nil && !minimock.Equal(*mm_want_ptrs.params, mm_got.params) {
				mmSaveGraphVersionWithMedia.t.Errorf("GraphVersionWriterMock.SaveGraphVersionWithMedia got unexpected parameter params, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSaveGraphVersionWithMedia.SaveGraphVersionWithMediaMock.defaultExpectation.expectationOrigins.originParams, *mm_want_ptrs.params, mm_got.params, minimock.Diff(*mm_want_ptrs.params, mm_got.params))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSaveGraphVersionWithMedia.t.Errorf("GraphVersionWriterMock.SaveGraphVersionWithMedia got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSaveGraphVersionWithMedia.SaveGraphVersionWithMediaMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSaveGraphVersionWithMedia.SaveGraphVersionWithMediaMock.defaultExpectation.results
		if mm_results == nil {
			mmSaveGraphVersionWithMedia.t.Fatal("No results are set for the GraphVersionWriterMock.SaveGraphVersionWithMedia")
		}
		return (*mm_results).err
	}
	if mmSaveGraphVersionWithMedia.funcSaveGraphVersionWithMedia != nil {
		return mmSaveGraphVersionWithMedia.funcSaveGraphVersionWithMedia(ctx, params)
	}
	mmSaveGraphVersionWithMedia.t.Fatalf("Unexpected call to GraphVersionWriterMock.SaveGraphVersionWithMedia. %v %v", ctx, params)
	return
}

// SaveGraphVersionWithMediaAfterCounter returns a count of finished GraphVersionWriterMock.SaveGraphVersionWithMedia invocations
func (mmSaveGraphVersionWithMedia *GraphVersionWriterMock) SaveGraphVersionWithMediaAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSaveGraphVersionWithMedia.afterSaveGraphVersionWithMediaCounter)
}

// SaveGraphVersionWithMediaBeforeCounter returns a count of GraphVersionWriterMock.SaveGraphVersionWithMedia invocations
func (mmSaveGraphVersionWithMedia *GraphVersionWriterMock) SaveGraphVersionWithMediaBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSaveGraphVersionWithMedia.beforeSaveGraphVersionWithMediaCounter)
}

// Calls returns a list of arguments used in each call to GraphVersionWriterMock.SaveGraphVersionWithMedia.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSaveGraphVersionWithMedia *mGraphVersionWriterMockSaveGraphVersionWithMedia) Calls() []*GraphVersionWriterMockSaveGraphVersionWithMediaParams {
	mmSaveGraphVersionWithMedia.mutex.RLock()

	argCopy := make([]*GraphVersionWriterMockSaveGraphVersionWithMediaParams, len(mmSaveGraphVersionWithMedia.callArgs))
	copy(argCopy, mmSaveGraphVersionWithMedia.callArgs)

	mmSaveGraphVersionWithMedia.mutex.RUnlock()

	return argCopy
}

// MinimockSaveGraphVersionWithMediaDone returns true if the count of the SaveGraphVersionWithMedia invocations corresponds
// the number of defined expectations
func (m *GraphVersionWriterMock) MinimockSaveGraphVersionWithMediaDone() bool {
	if m.SaveGraphVersionWithMediaMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SaveGraphVersionWithMediaMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SaveGraphVersionWithMediaMock.invocationsDone()
}

// MinimockSaveGraphVersionWithMediaInspect logs each unmet expectation
func (m *GraphVersionWriterMock) MinimockSaveGraphVersionWithMediaInspect() {
	for _, e := range m.SaveGraphVersionWithMediaMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to GraphVersionWriterMock.SaveGraphVersionWithMedia at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSaveGraphVersionWithMediaCounter := mm_atomic.LoadUint64(&m.afterSaveGraphVersionWithMediaCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SaveGraphVersionWithMediaMock.defaultExpectation != nil && afterSaveGraphVersionWithMediaCounter < 1 {
		if m.SaveGraphVersionWithMediaMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to GraphVersionWriterMock.SaveGraphVersionWithMedia at\n%s", m.SaveGraphVersionWithMediaMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to GraphVersionWriterMock.SaveGraphVersionWithMedia at\n%s with params: %#v", m.SaveGraphVersionWithMediaMock.defaultExpectation.expectationOrigins.origin, *m.SaveGraphVersionWithMediaMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSaveGraphVersionWithMedia != nil && afterSaveGraphVersionWithMediaCounter < 1 {
		m.t.Errorf("Expected call to GraphVersionWriterMock.SaveGraphVersionWithMedia at\n%s", m.funcSaveGraphVersionWithMediaOrigin)
	}

	if !m.SaveGraphVersionWithMediaMock.invocationsDone() && afterSaveGraphVersionWithMediaCounter > 0 {
		m.t.Errorf("Expected %d calls to GraphVersionWriterMock.SaveGraphVersionWithMedia at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SaveGraphVersionWithMediaMock.expectedInvocations), m.SaveGraphVersionWithMediaMock.expectedInvocationsOrigin, afterSaveGraphVersionWithMediaCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *GraphVersionWriterMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockSaveGraphVersionInspect()

			m.MinimockSaveGraphVersionWithMediaInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *GraphVersionWriterMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *GraphVersionWriterMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockSaveGraphVersionDone() &&
		m.MinimockSaveGraphVersionWithMediaDone()
}
