// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package portmock

//go:generate minimock -i sprezz/internal/domain/port.JSONLDParserPort -o jsonld_parser_mock.go -n JSONLDParserPortMock -p portmock

import (
	"context"
	"sprezz/internal/domain/model"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// JSONLDParserPortMock implements mm_port.JSONLDParserPort
type JSONLDParserPortMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcToQuads          func(ctx context.Context, graphID int64, mainObjectIRI string, jsonPayload []byte) (qa1 []model.Quad, err error)
	funcToQuadsOrigin    string
	inspectFuncToQuads   func(ctx context.Context, graphID int64, mainObjectIRI string, jsonPayload []byte)
	afterToQuadsCounter  uint64
	beforeToQuadsCounter uint64
	ToQuadsMock          mJSONLDParserPortMockToQuads
}

// NewJSONLDParserPortMock returns a mock for mm_port.JSONLDParserPort
func NewJSONLDParserPortMock(t minimock.Tester) *JSONLDParserPortMock {
	m := &JSONLDParserPortMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.ToQuadsMock = mJSONLDParserPortMockToQuads{mock: m}
	m.ToQuadsMock.callArgs = []*JSONLDParserPortMockToQuadsParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mJSONLDParserPortMockToQuads struct {
	optional           bool
	mock               *JSONLDParserPortMock
	defaultExpectation *JSONLDParserPortMockToQuadsExpectation
	expectations       []*JSONLDParserPortMockToQuadsExpectation

	callArgs []*JSONLDParserPortMockToQuadsParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// JSONLDParserPortMockToQuadsExpectation specifies expectation struct of the JSONLDParserPort.ToQuads
type JSONLDParserPortMockToQuadsExpectation struct {
	mock               *JSONLDParserPortMock
	params             *JSONLDParserPortMockToQuadsParams
	paramPtrs          *JSONLDParserPortMockToQuadsParamPtrs
	expectationOrigins JSONLDParserPortMockToQuadsExpectationOrigins
	results            *JSONLDParserPortMockToQuadsResults
	returnOrigin       string
	Counter            uint64
}

// JSONLDParserPortMockToQuadsParams contains parameters of the JSONLDParserPort.ToQuads
type JSONLDParserPortMockToQuadsParams struct {
	ctx           context.Context
	graphID       int64
	mainObjectIRI string
	jsonPayload   []byte
}

// JSONLDParserPortMockToQuadsParamPtrs contains pointers to parameters of the JSONLDParserPort.ToQuads
type JSONLDParserPortMockToQuadsParamPtrs struct {
	ctx           *context.Context
	graphID       *int64
	mainObjectIRI *string
	jsonPayload   *[]byte
}

// JSONLDParserPortMockToQuadsResults contains results of the JSONLDParserPort.ToQuads
type JSONLDParserPortMockToQuadsResults struct {
	qa1 []model.Quad
	err error
}

// JSONLDParserPortMockToQuadsOrigins contains origins of expectations of the JSONLDParserPort.ToQuads
type JSONLDParserPortMockToQuadsExpectationOrigins struct {
	origin              string
	originCtx           string
	originGraphID       string
	originMainObjectIRI string
	originJsonPayload   string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmToQuads *mJSONLDParserPortMockToQuads) Optional() *mJSONLDParserPortMockToQuads {
	mmToQuads.optional = true
	return mmToQuads
}

// Expect sets up expected params for JSONLDParserPort.ToQuads
func (mmToQuads *mJSONLDParserPortMockToQuads) Expect(ctx context.Context, graphID int64, mainObjectIRI string, jsonPayload []byte) *mJSONLDParserPortMockToQuads {
	if mmToQuads.mock.funcToQuads != nil {
		mmToQuads.mock.t.Fatalf("JSONLDParserPortMock.ToQuads mock is already set by Set")
	}

	if mmToQuads.defaultExpectation == nil {
		mmToQuads.defaultExpectation = &JSONLDParserPortMockToQuadsExpectation{}
	}

	if mmToQuads.defaultExpectation.paramPtrs != nil {
		mmToQuads.mock.t.Fatalf("JSONLDParserPortMock.ToQuads mock is already set by ExpectParams functions")
	}

	mmToQuads.defaultExpectation.params = &JSONLDParserPortMockToQuadsParams{ctx, graphID, mainObjectIRI, jsonPayload}
	mmToQuads.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmToQuads.expectations {
		if minimock.Equal(e.params, mmToQuads.defaultExpectation.params) {
			mmToQuads.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmToQuads.defaultExpectation.params)
		}
	}

	return mmToQuads
}

// ExpectCtxParam1 sets up expected param ctx for JSONLDParserPort.ToQuads
func (mmToQuads *mJSONLDParserPortMockToQuads) ExpectCtxParam1(ctx context.Context) *mJSONLDParserPortMockToQuads {
	if mmToQuads.mock.funcToQuads != nil {
		mmToQuads.mock.t.Fatalf("JSONLDParserPortMock.ToQuads mock is already set by Set")
	}

	if mmToQuads.defaultExpectation == nil {
		mmToQuads.defaultExpectation = &JSONLDParserPortMockToQuadsExpectation{}
	}

	if mmToQuads.defaultExpectation.params != nil {
		mmToQuads.mock.t.Fatalf("JSONLDParserPortMock.ToQuads mock is already set by Expect")
	}

	if mmToQuads.defaultExpectation.paramPtrs == nil {
		mmToQuads.defaultExpectation.paramPtrs = &JSONLDParserPortMockToQuadsParamPtrs{}
	}
	mmToQuads.defaultExpectation.paramPtrs.ctx = &ctx
	mmToQuads.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmToQuads
}

// ExpectGraphIDParam2 sets up expected param graphID for JSONLDParserPort.ToQuads
func (mmToQuads *mJSONLDParserPortMockToQuads) ExpectGraphIDParam2(graphID int64) *mJSONLDParserPortMockToQuads {
	if mmToQuads.mock.funcToQuads != nil {
		mmToQuads.mock.t.Fatalf("JSONLDParserPortMock.ToQuads mock is already set by Set")
	}

	if mmToQuads.defaultExpectation == nil {
		mmToQuads.defaultExpectation = &JSONLDParserPortMockToQuadsExpectation{}
	}

	if mmToQuads.defaultExpectation.params != nil {
		mmToQuads.mock.t.Fatalf("JSONLDParserPortMock.ToQuads mock is already set by Expect")
	}

	if mmToQuads.defaultExpectation.paramPtrs == nil {
		mmToQuads.defaultExpectation.paramPtrs = &JSONLDParserPortMockToQuadsParamPtrs{}
	}
	mmToQuads.defaultExpectation.paramPtrs.graphID = &graphID
	mmToQuads.defaultExpectation.expectationOrigins.originGraphID = minimock.CallerInfo(1)

	return mmToQuads
}

// ExpectMainObjectIRIParam3 sets up expected param mainObjectIRI for JSONLDParserPort.ToQuads
func (mmToQuads *mJSONLDParserPortMockToQuads) ExpectMainObjectIRIParam3(mainObjectIRI string) *mJSONLDParserPortMockToQuads {
	if mmToQuads.mock.funcToQuads != nil {
		mmToQuads.mock.t.Fatalf("JSONLDParserPortMock.ToQuads mock is already set by Set")
	}

	if mmToQuads.defaultExpectation == nil {
		mmToQuads.defaultExpectation = &JSONLDParserPortMockToQuadsExpectation{}
	}

	if mmToQuads.defaultExpectation.params != nil {
		mmToQuads.mock.t.Fatalf("JSONLDParserPortMock.ToQuads mock is already set by Expect")
	}

	if mmToQuads.defaultExpectation.paramPtrs == nil {
		mmToQuads.defaultExpectation.paramPtrs = &JSONLDParserPortMockToQuadsParamPtrs{}
	}
	mmToQuads.defaultExpectation.paramPtrs.mainObjectIRI = &mainObjectIRI
	mmToQuads.defaultExpectation.expectationOrigins.originMainObjectIRI = minimock.CallerInfo(1)

	return mmToQuads
}

// ExpectJsonPayloadParam4 sets up expected param jsonPayload for JSONLDParserPort.ToQuads
func (mmToQuads *mJSONLDParserPortMockToQuads) ExpectJsonPayloadParam4(jsonPayload []byte) *mJSONLDParserPortMockToQuads {
	if mmToQuads.mock.funcToQuads != nil {
		mmToQuads.mock.t.Fatalf("JSONLDParserPortMock.ToQuads mock is already set by Set")
	}

	if mmToQuads.defaultExpectation == nil {
		mmToQuads.defaultExpectation = &JSONLDParserPortMockToQuadsExpectation{}
	}

	if mmToQuads.defaultExpectation.params != nil {
		mmToQuads.mock.t.Fatalf("JSONLDParserPortMock.ToQuads mock is already set by Expect")
	}

	if mmToQuads.defaultExpectation.paramPtrs == nil {
		mmToQuads.defaultExpectation.paramPtrs = &JSONLDParserPortMockToQuadsParamPtrs{}
	}
	mmToQuads.defaultExpectation.paramPtrs.jsonPayload = &jsonPayload
	mmToQuads.defaultExpectation.expectationOrigins.originJsonPayload = minimock.CallerInfo(1)

	return mmToQuads
}

// Inspect accepts an inspector function that has same arguments as the JSONLDParserPort.ToQuads
func (mmToQuads *mJSONLDParserPortMockToQuads) Inspect(f func(ctx context.Context, graphID int64, mainObjectIRI string, jsonPayload []byte)) *mJSONLDParserPortMockToQuads {
	if mmToQuads.mock.inspectFuncToQuads != nil {
		mmToQuads.mock.t.Fatalf("Inspect function is already set for JSONLDParserPortMock.ToQuads")
	}

	mmToQuads.mock.inspectFuncToQuads = f

	return mmToQuads
}

// Return sets up results that will be returned by JSONLDParserPort.ToQuads
func (mmToQuads *mJSONLDParserPortMockToQuads) Return(qa1 []model.Quad, err error) *JSONLDParserPortMock {
	if mmToQuads.mock.funcToQuads != nil {
		mmToQuads.mock.t.Fatalf("JSONLDParserPortMock.ToQuads mock is already set by Set")
	}

	if mmToQuads.defaultExpectation == nil {
		mmToQuads.defaultExpectation = &JSONLDParserPortMockToQuadsExpectation{mock: mmToQuads.mock}
	}
	mmToQuads.defaultExpectation.results = &JSONLDParserPortMockToQuadsResults{qa1, err}
	mmToQuads.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmToQuads.mock
}

// Set uses given function f to mock the JSONLDParserPort.ToQuads method
func (mmToQuads *mJSONLDParserPortMockToQuads) Set(f func(ctx context.Context, graphID int64, mainObjectIRI string, jsonPayload []byte) (qa1 []model.Quad, err error)) *JSONLDParserPortMock {
	if mmToQuads.defaultExpectation != nil {
		mmToQuads.mock.t.Fatalf("Default expectation is already set for the JSONLDParserPort.ToQuads method")
	}

	if len(mmToQuads.expectations) > 0 {
		mmToQuads.mock.t.Fatalf("Some expectations are already set for the JSONLDParserPort.ToQuads method")
	}

	mmToQuads.mock.funcToQuads = f
	mmToQuads.mock.funcToQuadsOrigin = minimock.CallerInfo(1)
	return mmToQuads.mock
}

// When sets expectation for the JSONLDParserPort.ToQuads which will trigger the result defined by the following
// Then helper
func (mmToQuads *mJSONLDParserPortMockToQuads) When(ctx context.Context, graphID int64, mainObjectIRI string, jsonPayload []byte) *JSONLDParserPortMockToQuadsExpectation {
	if mmToQuads.mock.funcToQuads != nil {
		mmToQuads.mock.t.Fatalf("JSONLDParserPortMock.ToQuads mock is already set by Set")
	}

	expectation := &JSONLDParserPortMockToQuadsExpectation{
		mock:               mmToQuads.mock,
		params:             &JSONLDParserPortMockToQuadsParams{ctx, graphID, mainObjectIRI, jsonPayload},
		expectationOrigins: JSONLDParserPortMockToQuadsExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmToQuads.expectations = append(mmToQuads.expectations, expectation)
	return expectation
}

// Then sets up JSONLDParserPort.ToQuads return parameters for the expectation previously defined by the When method
func (e *JSONLDParserPortMockToQuadsExpectation) Then(qa1 []model.Quad, err error) *JSONLDParserPortMock {
	e.results = &JSONLDParserPortMockToQuadsResults{qa1, err}
	return e.mock
}

// Times sets number of times JSONLDParserPort.ToQuads should be invoked
func (mmToQuads *mJSONLDParserPortMockToQuads) Times(n uint64) *mJSONLDParserPortMockToQuads {
	if n == 0 {
		mmToQuads.mock.t.Fatalf("Times of JSONLDParserPortMock.ToQuads mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmToQuads.expectedInvocations, n)
	mmToQuads.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmToQuads
}

func (mmToQuads *mJSONLDParserPortMockToQuads) invocationsDone() bool {
	if len(mmToQuads.expectations) == 0 && mmToQuads.defaultExpectation == nil && mmToQuads.mock.funcToQuads == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmToQuads.mock.afterToQuadsCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmToQuads.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ToQuads implements mm_port.JSONLDParserPort
func (mmToQuads *JSONLDParserPortMock) ToQuads(ctx context.Context, graphID int64, mainObjectIRI string, jsonPayload []byte) (qa1 []model.Quad, err error) {
	mm_atomic.AddUint64(&mmToQuads.beforeToQuadsCounter, 1)
	defer mm_atomic.AddUint64(&mmToQuads.afterToQuadsCounter, 1)

	mmToQuads.t.Helper()

	if mmToQuads.inspectFuncToQuads != nil {
		mmToQuads.inspectFuncToQuads(ctx, graphID, mainObjectIRI, jsonPayload)
	}

	mm_params := JSONLDParserPortMockToQuadsParams{ctx, graphID, mainObjectIRI, jsonPayload}

	// Record call args
	mmToQuads.ToQuadsMock.mutex.Lock()
	mmToQuads.ToQuadsMock.callArgs = append(mmToQuads.ToQuadsMock.callArgs, &mm_params)
	mmToQuads.ToQuadsMock.mutex.Unlock()

	for _, e := range mmToQuads.ToQuadsMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.qa1, e.results.err
		}
	}

	if mmToQuads.ToQuadsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmToQuads.ToQuadsMock.defaultExpectation.Counter, 1)
		mm_want := mmToQuads.ToQuadsMock.defaultExpectation.params
		mm_want_ptrs := mmToQuads.ToQuadsMock.defaultExpectation.paramPtrs

		mm_got := JSONLDParserPortMockToQuadsParams{ctx, graphID, mainObjectIRI, jsonPayload}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmToQuads.t.Errorf("JSONLDParserPortMock.ToQuads got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmToQuads.ToQuadsMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.graphID != nil && !minimock.Equal(*mm_want_ptrs.graphID, mm_got.graphID) {
				mmToQuads.t.Errorf("JSONLDParserPortMock.ToQuads got unexpected parameter graphID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmToQuads.ToQuadsMock.defaultExpectation.expectationOrigins.originGraphID, *mm_want_ptrs.graphID, mm_got.graphID, minimock.Diff(*mm_want_ptrs.graphID, mm_got.graphID))
			}

			if mm_want_ptrs.mainObjectIRI != nil && !minimock.Equal(*mm_want_ptrs.mainObjectIRI, mm_got.mainObjectIRI) {
				mmToQuads.t.Errorf("JSONLDParserPortMock.ToQuads got unexpected parameter mainObjectIRI, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmToQuads.ToQuadsMock.defaultExpectation.expectationOrigins.originMainObjectIRI, *mm_want_ptrs.mainObjectIRI, mm_got.mainObjectIRI, minimock.Diff(*mm_want_ptrs.mainObjectIRI, mm_got.mainObjectIRI))
			}

			if mm_want_ptrs.jsonPayload != nil && !minimock.Equal(*mm_want_ptrs.jsonPayload, mm_got.jsonPayload) {
				mmToQuads.t.Errorf("JSONLDParserPortMock.ToQuads got unexpected parameter jsonPayload, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmToQuads.ToQuadsMock.defaultExpectation.expectationOrigins.originJsonPayload, *mm_want_ptrs.jsonPayload, mm_got.jsonPayload, minimock.Diff(*mm_want_ptrs.jsonPayload, mm_got.jsonPayload))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmToQuads.t.Errorf("JSONLDParserPortMock.ToQuads got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmToQuads.ToQuadsMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmToQuads.ToQuadsMock.defaultExpectation.results
		if mm_results == nil {
			mmToQuads.t.Fatal("No results are set for the JSONLDParserPortMock.ToQuads")
		}
		return (*mm_results).qa1, (*mm_results).err
	}
	if mmToQuads.funcToQuads != nil {
		return mmToQuads.funcToQuads(ctx, graphID, mainObjectIRI, jsonPayload)
	}
	mmToQuads.t.Fatalf("Unexpected call to JSONLDParserPortMock.ToQuads. %v %v %v %v", ctx, graphID, mainObjectIRI, jsonPayload)
	return
}

// ToQuadsAfterCounter returns a count of finished JSONLDParserPortMock.ToQuads invocations
func (mmToQuads *JSONLDParserPortMock) ToQuadsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmToQuads.afterToQuadsCounter)
}

// ToQuadsBeforeCounter returns a count of JSONLDParserPortMock.ToQuads invocations
func (mmToQuads *JSONLDParserPortMock) ToQuadsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmToQuads.beforeToQuadsCounter)
}

// Calls returns a list of arguments used in each call to JSONLDParserPortMock.ToQuads.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmToQuads *mJSONLDParserPortMockToQuads) Calls() []*JSONLDParserPortMockToQuadsParams {
	mmToQuads.mutex.RLock()

	argCopy := make([]*JSONLDParserPortMockToQuadsParams, len(mmToQuads.callArgs))
	copy(argCopy, mmToQuads.callArgs)

	mmToQuads.mutex.RUnlock()

	return argCopy
}

// MinimockToQuadsDone returns true if the count of the ToQuads invocations corresponds
// the number of defined expectations
func (m *JSONLDParserPortMock) MinimockToQuadsDone() bool {
	if m.ToQuadsMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ToQuadsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ToQuadsMock.invocationsDone()
}

// MinimockToQuadsInspect logs each unmet expectation
func (m *JSONLDParserPortMock) MinimockToQuadsInspect() {
	for _, e := range m.ToQuadsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to JSONLDParserPortMock.ToQuads at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterToQuadsCounter := mm_atomic.LoadUint64(&m.afterToQuadsCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ToQuadsMock.defaultExpectation != nil && afterToQuadsCounter < 1 {
		if m.ToQuadsMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to JSONLDParserPortMock.ToQuads at\n%s", m.ToQuadsMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to JSONLDParserPortMock.ToQuads at\n%s with params: %#v", m.ToQuadsMock.defaultExpectation.expectationOrigins.origin, *m.ToQuadsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcToQuads != nil && afterToQuadsCounter < 1 {
		m.t.Errorf("Expected call to JSONLDParserPortMock.ToQuads at\n%s", m.funcToQuadsOrigin)
	}

	if !m.ToQuadsMock.invocationsDone() && afterToQuadsCounter > 0 {
		m.t.Errorf("Expected %d calls to JSONLDParserPortMock.ToQuads at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ToQuadsMock.expectedInvocations), m.ToQuadsMock.expectedInvocationsOrigin, afterToQuadsCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *JSONLDParserPortMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockToQuadsInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *JSONLDParserPortMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *JSONLDParserPortMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockToQuadsDone()
}
