// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package portmock

//go:generate minimock -i sprezz/internal/domain/port.MediaStoragePort -o media_storage_mock.go -n MediaStoragePortMock -p portmock

import (
	"context"
	"io"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// MediaStoragePortMock implements mm_port.MediaStoragePort
type MediaStoragePortMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcDeleteObject          func(ctx context.Context, objectName string) (err error)
	funcDeleteObjectOrigin    string
	inspectFuncDeleteObject   func(ctx context.Context, objectName string)
	afterDeleteObjectCounter  uint64
	beforeDeleteObjectCounter uint64
	DeleteObjectMock          mMediaStoragePortMockDeleteObject

	funcPutObject          func(ctx context.Context, objectName string, reader io.Reader, contentType string) (objectKey string, sha256Hex string, err error)
	funcPutObjectOrigin    string
	inspectFuncPutObject   func(ctx context.Context, objectName string, reader io.Reader, contentType string)
	afterPutObjectCounter  uint64
	beforePutObjectCounter uint64
	PutObjectMock          mMediaStoragePortMockPutObject
}

// NewMediaStoragePortMock returns a mock for mm_port.MediaStoragePort
func NewMediaStoragePortMock(t minimock.Tester) *MediaStoragePortMock {
	m := &MediaStoragePortMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.DeleteObjectMock = mMediaStoragePortMockDeleteObject{mock: m}
	m.DeleteObjectMock.callArgs = []*MediaStoragePortMockDeleteObjectParams{}

	m.PutObjectMock = mMediaStoragePortMockPutObject{mock: m}
	m.PutObjectMock.callArgs = []*MediaStoragePortMockPutObjectParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mMediaStoragePortMockDeleteObject struct {
	optional           bool
	mock               *MediaStoragePortMock
	defaultExpectation *MediaStoragePortMockDeleteObjectExpectation
	expectations       []*MediaStoragePortMockDeleteObjectExpectation

	callArgs []*MediaStoragePortMockDeleteObjectParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// MediaStoragePortMockDeleteObjectExpectation specifies expectation struct of the MediaStoragePort.DeleteObject
type MediaStoragePortMockDeleteObjectExpectation struct {
	mock               *MediaStoragePortMock
	params             *MediaStoragePortMockDeleteObjectParams
	paramPtrs          *MediaStoragePortMockDeleteObjectParamPtrs
	expectationOrigins MediaStoragePortMockDeleteObjectExpectationOrigins
	results            *MediaStoragePortMockDeleteObjectResults
	returnOrigin       string
	Counter            uint64
}

// MediaStoragePortMockDeleteObjectParams contains parameters of the MediaStoragePort.DeleteObject
type MediaStoragePortMockDeleteObjectParams struct {
	ctx        context.Context
	objectName string
}

// MediaStoragePortMockDeleteObjectParamPtrs contains pointers to parameters of the MediaStoragePort.DeleteObject
type MediaStoragePortMockDeleteObjectParamPtrs struct {
	ctx        *context.Context
	objectName *string
}

// MediaStoragePortMockDeleteObjectResults contains results of the MediaStoragePort.DeleteObject
type MediaStoragePortMockDeleteObjectResults struct {
	err error
}

// MediaStoragePortMockDeleteObjectOrigins contains origins of expectations of the MediaStoragePort.DeleteObject
type MediaStoragePortMockDeleteObjectExpectationOrigins struct {
	origin           string
	originCtx        string
	originObjectName string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDeleteObject *mMediaStoragePortMockDeleteObject) Optional() *mMediaStoragePortMockDeleteObject {
	mmDeleteObject.optional = true
	return mmDeleteObject
}

// Expect sets up expected params for MediaStoragePort.DeleteObject
func (mmDeleteObject *mMediaStoragePortMockDeleteObject) Expect(ctx context.Context, objectName string) *mMediaStoragePortMockDeleteObject {
	if mmDeleteObject.mock.funcDeleteObject != nil {
		mmDeleteObject.mock.t.Fatalf("MediaStoragePortMock.DeleteObject mock is already set by Set")
	}

	if mmDeleteObject.defaultExpectation == nil {
		mmDeleteObject.defaultExpectation = &MediaStoragePortMockDeleteObjectExpectation{}
	}

	if mmDeleteObject.defaultExpectation.paramPtrs != nil {
		mmDeleteObject.mock.t.Fatalf("MediaStoragePortMock.DeleteObject mock is already set by ExpectParams functions")
	}

	mmDeleteObject.defaultExpectation.params = &MediaStoragePortMockDeleteObjectParams{ctx, objectName}
	mmDeleteObject.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDeleteObject.expectations {
		if minimock.Equal(e.params, mmDeleteObject.defaultExpectation.params) {
			mmDeleteObject.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDeleteObject.defaultExpectation.params)
		}
	}

	return mmDeleteObject
}

// ExpectCtxParam1 sets up expected param ctx for MediaStoragePort.DeleteObject
func (mmDeleteObject *mMediaStoragePortMockDeleteObject) ExpectCtxParam1(ctx context.Context) *mMediaStoragePortMockDeleteObject {
	if mmDeleteObject.mock.funcDeleteObject != nil {
		mmDeleteObject.mock.t.Fatalf("MediaStoragePortMock.DeleteObject mock is already set by Set")
	}

	if mmDeleteObject.defaultExpectation == nil {
		mmDeleteObject.defaultExpectation = &MediaStoragePortMockDeleteObjectExpectation{}
	}

	if mmDeleteObject.defaultExpectation.params != nil {
		mmDeleteObject.mock.t.Fatalf("MediaStoragePortMock.DeleteObject mock is already set by Expect")
	}

	if mmDeleteObject.defaultExpectation.paramPtrs == nil {
		mmDeleteObject.defaultExpectation.paramPtrs = &MediaStoragePortMockDeleteObjectParamPtrs{}
	}
	mmDeleteObject.defaultExpectation.paramPtrs.ctx = &ctx
	mmDeleteObject.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDeleteObject
}

// ExpectObjectNameParam2 sets up expected param objectName for MediaStoragePort.DeleteObject
func (mmDeleteObject *mMediaStoragePortMockDeleteObject) ExpectObjectNameParam2(objectName string) *mMediaStoragePortMockDeleteObject {
	if mmDeleteObject.mock.funcDeleteObject != nil {
		mmDeleteObject.mock.t.Fatalf("MediaStoragePortMock.DeleteObject mock is already set by Set")
	}

	if mmDeleteObject.defaultExpectation == nil {
		mmDeleteObject.defaultExpectation = &MediaStoragePortMockDeleteObjectExpectation{}
	}

	if mmDeleteObject.defaultExpectation.params != nil {
		mmDeleteObject.mock.t.Fatalf("MediaStoragePortMock.DeleteObject mock is already set by Expect")
	}

	if mmDeleteObject.defaultExpectation.paramPtrs == nil {
		mmDeleteObject.defaultExpectation.paramPtrs = &MediaStoragePortMockDeleteObjectParamPtrs{}
	}
	mmDeleteObject.defaultExpectation.paramPtrs.objectName = &objectName
	mmDeleteObject.defaultExpectation.expectationOrigins.originObjectName = minimock.CallerInfo(1)

	return mmDeleteObject
}

// Inspect accepts an inspector function that has same arguments as the MediaStoragePort.DeleteObject
func (mmDeleteObject *mMediaStoragePortMockDeleteObject) Inspect(f func(ctx context.Context, objectName string)) *mMediaStoragePortMockDeleteObject {
	if mmDeleteObject.mock.inspectFuncDeleteObject != nil {
		mmDeleteObject.mock.t.Fatalf("Inspect function is already set for MediaStoragePortMock.DeleteObject")
	}

	mmDeleteObject.mock.inspectFuncDeleteObject = f

	return mmDeleteObject
}

// Return sets up results that will be returned by MediaStoragePort.DeleteObject
func (mmDeleteObject *mMediaStoragePortMockDeleteObject) Return(err error) *MediaStoragePortMock {
	if mmDeleteObject.mock.funcDeleteObject != nil {
		mmDeleteObject.mock.t.Fatalf("MediaStoragePortMock.DeleteObject mock is already set by Set")
	}

	if mmDeleteObject.defaultExpectation == nil {
		mmDeleteObject.defaultExpectation = &MediaStoragePortMockDeleteObjectExpectation{mock: mmDeleteObject.mock}
	}
	mmDeleteObject.defaultExpectation.results = &MediaStoragePortMockDeleteObjectResults{err}
	mmDeleteObject.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDeleteObject.mock
}

// Set uses given function f to mock the MediaStoragePort.DeleteObject method
func (mmDeleteObject *mMediaStoragePortMockDeleteObject) Set(f func(ctx context.Context, objectName string) (err error)) *MediaStoragePortMock {
	if mmDeleteObject.defaultExpectation != nil {
		mmDeleteObject.mock.t.Fatalf("Default expectation is already set for the MediaStoragePort.DeleteObject method")
	}

	if len(mmDeleteObject.expectations) > 0 {
		mmDeleteObject.mock.t.Fatalf("Some expectations are already set for the MediaStoragePort.DeleteObject method")
	}

	mmDeleteObject.mock.funcDeleteObject = f
	mmDeleteObject.mock.funcDeleteObjectOrigin = minimock.CallerInfo(1)
	return mmDeleteObject.mock
}

// When sets expectation for the MediaStoragePort.DeleteObject which will trigger the result defined by the following
// Then helper
func (mmDeleteObject *mMediaStoragePortMockDeleteObject) When(ctx context.Context, objectName string) *MediaStoragePortMockDeleteObjectExpectation {
	if mmDeleteObject.mock.funcDeleteObject != nil {
		mmDeleteObject.mock.t.Fatalf("MediaStoragePortMock.DeleteObject mock is already set by Set")
	}

	expectation := &MediaStoragePortMockDeleteObjectExpectation{
		mock:               mmDeleteObject.mock,
		params:             &MediaStoragePortMockDeleteObjectParams{ctx, objectName},
		expectationOrigins: MediaStoragePortMockDeleteObjectExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDeleteObject.expectations = append(mmDeleteObject.expectations, expectation)
	return expectation
}

// Then sets up MediaStoragePort.DeleteObject return parameters for the expectation previously defined by the When method
func (e *MediaStoragePortMockDeleteObjectExpectation) Then(err error) *MediaStoragePortMock {
	e.results = &MediaStoragePortMockDeleteObjectResults{err}
	return e.mock
}

// Times sets number of times MediaStoragePort.DeleteObject should be invoked
func (mmDeleteObject *mMediaStoragePortMockDeleteObject) Times(n uint64) *mMediaStoragePortMockDeleteObject {
	if n == 0 {
		mmDeleteObject.mock.t.Fatalf("Times of MediaStoragePortMock.DeleteObject mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDeleteObject.expectedInvocations, n)
	mmDeleteObject.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDeleteObject
}

func (mmDeleteObject *mMediaStoragePortMockDeleteObject) invocationsDone() bool {
	if len(mmDeleteObject.expectations) == 0 && mmDeleteObject.defaultExpectation == nil && mmDeleteObject.mock.funcDeleteObject == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDeleteObject.mock.afterDeleteObjectCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDeleteObject.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// DeleteObject implements mm_port.MediaStoragePort
func (mmDeleteObject *MediaStoragePortMock) DeleteObject(ctx context.Context, objectName string) (err error) {
	mm_atomic.AddUint64(&mmDeleteObject.beforeDeleteObjectCounter, 1)
	defer mm_atomic.AddUint64(&mmDeleteObject.afterDeleteObjectCounter, 1)

	mmDeleteObject.t.Helper()

	if mmDeleteObject.inspectFuncDeleteObject != nil {
		mmDeleteObject.inspectFuncDeleteObject(ctx, objectName)
	}

	mm_params := MediaStoragePortMockDeleteObjectParams{ctx, objectName}

	// Record call args
	mmDeleteObject.DeleteObjectMock.mutex.Lock()
	mmDeleteObject.DeleteObjectMock.callArgs = append(mmDeleteObject.DeleteObjectMock.callArgs, &mm_params)
	mmDeleteObject.DeleteObjectMock.mutex.Unlock()

	for _, e := range mmDeleteObject.DeleteObjectMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDeleteObject.DeleteObjectMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDeleteObject.DeleteObjectMock.defaultExpectation.Counter, 1)
		mm_want := mmDeleteObject.DeleteObjectMock.defaultExpectation.params
		mm_want_ptrs := mmDeleteObject.DeleteObjectMock.defaultExpectation.paramPtrs

		mm_got := MediaStoragePortMockDeleteObjectParams{ctx, objectName}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDeleteObject.t.Errorf("MediaStoragePortMock.DeleteObject got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteObject.DeleteObjectMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.objectName != nil && !minimock.Equal(*mm_want_ptrs.objectName, mm_got.objectName) {
				mmDeleteObject.t.Errorf("MediaStoragePortMock.DeleteObject got unexpected parameter objectName, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteObject.DeleteObjectMock.defaultExpectation.expectationOrigins.originObjectName, *mm_want_ptrs.objectName, mm_got.objectName, minimock.Diff(*mm_want_ptrs.objectName, mm_got.objectName))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDeleteObject.t.Errorf("MediaStoragePortMock.DeleteObject got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDeleteObject.DeleteObjectMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDeleteObject.DeleteObjectMock.defaultExpectation.results
		if mm_results == nil {
			mmDeleteObject.t.Fatal("No results are set for the MediaStoragePortMock.DeleteObject")
		}
		return (*mm_results).err
	}
	if mmDeleteObject.funcDeleteObject != nil {
		return mmDeleteObject.funcDeleteObject(ctx, objectName)
	}
	mmDeleteObject.t.Fatalf("Unexpected call to MediaStoragePortMock.DeleteObject. %v %v", ctx, objectName)
	return
}

// DeleteObjectAfterCounter returns a count of finished MediaStoragePortMock.DeleteObject invocations
func (mmDeleteObject *MediaStoragePortMock) DeleteObjectAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteObject.afterDeleteObjectCounter)
}

// DeleteObjectBeforeCounter returns a count of MediaStoragePortMock.DeleteObject invocations
func (mmDeleteObject *MediaStoragePortMock) DeleteObjectBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteObject.beforeDeleteObjectCounter)
}

// Calls returns a list of arguments used in each call to MediaStoragePortMock.DeleteObject.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDeleteObject *mMediaStoragePortMockDeleteObject) Calls() []*MediaStoragePortMockDeleteObjectParams {
	mmDeleteObject.mutex.RLock()

	argCopy := make([]*MediaStoragePortMockDeleteObjectParams, len(mmDeleteObject.callArgs))
	copy(argCopy, mmDeleteObject.callArgs)

	mmDeleteObject.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteObjectDone returns true if the count of the DeleteObject invocations corresponds
// the number of defined expectations
func (m *MediaStoragePortMock) MinimockDeleteObjectDone() bool {
	if m.DeleteObjectMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteObjectMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteObjectMock.invocationsDone()
}

// MinimockDeleteObjectInspect logs each unmet expectation
func (m *MediaStoragePortMock) MinimockDeleteObjectInspect() {
	for _, e := range m.DeleteObjectMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to MediaStoragePortMock.DeleteObject at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteObjectCounter := mm_atomic.LoadUint64(&m.afterDeleteObjectCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteObjectMock.defaultExpectation != nil && afterDeleteObjectCounter < 1 {
		if m.DeleteObjectMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to MediaStoragePortMock.DeleteObject at\n%s", m.DeleteObjectMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to MediaStoragePortMock.DeleteObject at\n%s with params: %#v", m.DeleteObjectMock.defaultExpectation.expectationOrigins.origin, *m.DeleteObjectMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDeleteObject != nil && afterDeleteObjectCounter < 1 {
		m.t.Errorf("Expected call to MediaStoragePortMock.DeleteObject at\n%s", m.funcDeleteObjectOrigin)
	}

	if !m.DeleteObjectMock.invocationsDone() && afterDeleteObjectCounter > 0 {
		m.t.Errorf("Expected %d calls to MediaStoragePortMock.DeleteObject at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteObjectMock.expectedInvocations), m.DeleteObjectMock.expectedInvocationsOrigin, afterDeleteObjectCounter)
	}
}

type mMediaStoragePortMockPutObject struct {
	optional           bool
	mock               *MediaStoragePortMock
	defaultExpectation *MediaStoragePortMockPutObjectExpectation
	expectations       []*MediaStoragePortMockPutObjectExpectation

	callArgs []*MediaStoragePortMockPutObjectParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// MediaStoragePortMockPutObjectExpectation specifies expectation struct of the MediaStoragePort.PutObject
type MediaStoragePortMockPutObjectExpectation struct {
	mock               *MediaStoragePortMock
	params             *MediaStoragePortMockPutObjectParams
	paramPtrs          *MediaStoragePortMockPutObjectParamPtrs
	expectationOrigins MediaStoragePortMockPutObjectExpectationOrigins
	results            *MediaStoragePortMockPutObjectResults
	returnOrigin       string
	Counter            uint64
}

// MediaStoragePortMockPutObjectParams contains parameters of the MediaStoragePort.PutObject
type MediaStoragePortMockPutObjectParams struct {
	ctx         context.Context
	objectName  string
	reader      io.Reader
	contentType string
}

// MediaStoragePortMockPutObjectParamPtrs contains pointers to parameters of the MediaStoragePort.PutObject
type MediaStoragePortMockPutObjectParamPtrs struct {
	ctx         *context.Context
	objectName  *string
	reader      *io.Reader
	contentType *string
}

// MediaStoragePortMockPutObjectResults contains results of the MediaStoragePort.PutObject
type MediaStoragePortMockPutObjectResults struct {
	objectKey string
	sha256Hex string
	err       error
}

// MediaStoragePortMockPutObjectOrigins contains origins of expectations of the MediaStoragePort.PutObject
type MediaStoragePortMockPutObjectExpectationOrigins struct {
	origin            string
	originCtx         string
	originObjectName  string
	originReader      string
	originContentType string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmPutObject *mMediaStoragePortMockPutObject) Optional() *mMediaStoragePortMockPutObject {
	mmPutObject.optional = true
	return mmPutObject
}

// Expect sets up expected params for MediaStoragePort.PutObject
func (mmPutObject *mMediaStoragePortMockPutObject) Expect(ctx context.Context, objectName string, reader io.Reader, contentType string) *mMediaStoragePortMockPutObject {
	if mmPutObject.mock.funcPutObject != nil {
		mmPutObject.mock.t.Fatalf("MediaStoragePortMock.PutObject mock is already set by Set")
	}

	if mmPutObject.defaultExpectation == nil {
		mmPutObject.defaultExpectation = &MediaStoragePortMockPutObjectExpectation{}
	}

	if mmPutObject.defaultExpectation.paramPtrs != nil {
		mmPutObject.mock.t.Fatalf("MediaStoragePortMock.PutObject mock is already set by ExpectParams functions")
	}

	mmPutObject.defaultExpectation.params = &MediaStoragePortMockPutObjectParams{ctx, objectName, reader, contentType}
	mmPutObject.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmPutObject.expectations {
		if minimock.Equal(e.params, mmPutObject.defaultExpectation.params) {
			mmPutObject.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmPutObject.defaultExpectation.params)
		}
	}

	return mmPutObject
}

// ExpectCtxParam1 sets up expected param ctx for MediaStoragePort.PutObject
func (mmPutObject *mMediaStoragePortMockPutObject) ExpectCtxParam1(ctx context.Context) *mMediaStoragePortMockPutObject {
	if mmPutObject.mock.funcPutObject != nil {
		mmPutObject.mock.t.Fatalf("MediaStoragePortMock.PutObject mock is already set by Set")
	}

	if mmPutObject.defaultExpectation == nil {
		mmPutObject.defaultExpectation = &MediaStoragePortMockPutObjectExpectation{}
	}

	if mmPutObject.defaultExpectation.params != nil {
		mmPutObject.mock.t.Fatalf("MediaStoragePortMock.PutObject mock is already set by Expect")
	}

	if mmPutObject.defaultExpectation.paramPtrs == nil {
		mmPutObject.defaultExpectation.paramPtrs = &MediaStoragePortMockPutObjectParamPtrs{}
	}
	mmPutObject.defaultExpectation.paramPtrs.ctx = &ctx
	mmPutObject.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmPutObject
}

// ExpectObjectNameParam2 sets up expected param objectName for MediaStoragePort.PutObject
func (mmPutObject *mMediaStoragePortMockPutObject) ExpectObjectNameParam2(objectName string) *mMediaStoragePortMockPutObject {
	if mmPutObject.mock.funcPutObject != nil {
		mmPutObject.mock.t.Fatalf("MediaStoragePortMock.PutObject mock is already set by Set")
	}

	if mmPutObject.defaultExpectation == nil {
		mmPutObject.defaultExpectation = &MediaStoragePortMockPutObjectExpectation{}
	}

	if mmPutObject.defaultExpectation.params != nil {
		mmPutObject.mock.t.Fatalf("MediaStoragePortMock.PutObject mock is already set by Expect")
	}

	if mmPutObject.defaultExpectation.paramPtrs == nil {
		mmPutObject.defaultExpectation.paramPtrs = &MediaStoragePortMockPutObjectParamPtrs{}
	}
	mmPutObject.defaultExpectation.paramPtrs.objectName = &objectName
	mmPutObject.defaultExpectation.expectationOrigins.originObjectName = minimock.CallerInfo(1)

	return mmPutObject
}

// ExpectReaderParam3 sets up expected param reader for MediaStoragePort.PutObject
func (mmPutObject *mMediaStoragePortMockPutObject) ExpectReaderParam3(reader io.Reader) *mMediaStoragePortMockPutObject {
	if mmPutObject.mock.funcPutObject != nil {
		mmPutObject.mock.t.Fatalf("MediaStoragePortMock.PutObject mock is already set by Set")
	}

	if mmPutObject.defaultExpectation == nil {
		mmPutObject.defaultExpectation = &MediaStoragePortMockPutObjectExpectation{}
	}

	if mmPutObject.defaultExpectation.params != nil {
		mmPutObject.mock.t.Fatalf("MediaStoragePortMock.PutObject mock is already set by Expect")
	}

	if mmPutObject.defaultExpectation.paramPtrs == nil {
		mmPutObject.defaultExpectation.paramPtrs = &MediaStoragePortMockPutObjectParamPtrs{}
	}
	mmPutObject.defaultExpectation.paramPtrs.reader = &reader
	mmPutObject.defaultExpectation.expectationOrigins.originReader = minimock.CallerInfo(1)

	return mmPutObject
}

// ExpectContentTypeParam4 sets up expected param contentType for MediaStoragePort.PutObject
func (mmPutObject *mMediaStoragePortMockPutObject) ExpectContentTypeParam4(contentType string) *mMediaStoragePortMockPutObject {
	if mmPutObject.mock.funcPutObject != nil {
		mmPutObject.mock.t.Fatalf("MediaStoragePortMock.PutObject mock is already set by Set")
	}

	if mmPutObject.defaultExpectation == nil {
		mmPutObject.defaultExpectation = &MediaStoragePortMockPutObjectExpectation{}
	}

	if mmPutObject.defaultExpectation.params != nil {
		mmPutObject.mock.t.Fatalf("MediaStoragePortMock.PutObject mock is already set by Expect")
	}

	if mmPutObject.defaultExpectation.paramPtrs == nil {
		mmPutObject.defaultExpectation.paramPtrs = &MediaStoragePortMockPutObjectParamPtrs{}
	}
	mmPutObject.defaultExpectation.paramPtrs.contentType = &contentType
	mmPutObject.defaultExpectation.expectationOrigins.originContentType = minimock.CallerInfo(1)

	return mmPutObject
}

// Inspect accepts an inspector function that has same arguments as the MediaStoragePort.PutObject
func (mmPutObject *mMediaStoragePortMockPutObject) Inspect(f func(ctx context.Context, objectName string, reader io.Reader, contentType string)) *mMediaStoragePortMockPutObject {
	if mmPutObject.mock.inspectFuncPutObject != nil {
		mmPutObject.mock.t.Fatalf("Inspect function is already set for MediaStoragePortMock.PutObject")
	}

	mmPutObject.mock.inspectFuncPutObject = f

	return mmPutObject
}

// Return sets up results that will be returned by MediaStoragePort.PutObject
func (mmPutObject *mMediaStoragePortMockPutObject) Return(objectKey string, sha256Hex string, err error) *MediaStoragePortMock {
	if mmPutObject.mock.funcPutObject != nil {
		mmPutObject.mock.t.Fatalf("MediaStoragePortMock.PutObject mock is already set by Set")
	}

	if mmPutObject.defaultExpectation == nil {
		mmPutObject.defaultExpectation = &MediaStoragePortMockPutObjectExpectation{mock: mmPutObject.mock}
	}
	mmPutObject.defaultExpectation.results = &MediaStoragePortMockPutObjectResults{objectKey, sha256Hex, err}
	mmPutObject.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmPutObject.mock
}

// Set uses given function f to mock the MediaStoragePort.PutObject method
func (mmPutObject *mMediaStoragePortMockPutObject) Set(f func(ctx context.Context, objectName string, reader io.Reader, contentType string) (objectKey string, sha256Hex string, err error)) *MediaStoragePortMock {
	if mmPutObject.defaultExpectation != nil {
		mmPutObject.mock.t.Fatalf("Default expectation is already set for the MediaStoragePort.PutObject method")
	}

	if len(mmPutObject.expectations) > 0 {
		mmPutObject.mock.t.Fatalf("Some expectations are already set for the MediaStoragePort.PutObject method")
	}

	mmPutObject.mock.funcPutObject = f
	mmPutObject.mock.funcPutObjectOrigin = minimock.CallerInfo(1)
	return mmPutObject.mock
}

// When sets expectation for the MediaStoragePort.PutObject which will trigger the result defined by the following
// Then helper
func (mmPutObject *mMediaStoragePortMockPutObject) When(ctx context.Context, objectName string, reader io.Reader, contentType string) *MediaStoragePortMockPutObjectExpectation {
	if mmPutObject.mock.funcPutObject != nil {
		mmPutObject.mock.t.Fatalf("MediaStoragePortMock.PutObject mock is already set by Set")
	}

	expectation := &MediaStoragePortMockPutObjectExpectation{
		mock:               mmPutObject.mock,
		params:             &MediaStoragePortMockPutObjectParams{ctx, objectName, reader, contentType},
		expectationOrigins: MediaStoragePortMockPutObjectExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmPutObject.expectations = append(mmPutObject.expectations, expectation)
	return expectation
}

// Then sets up MediaStoragePort.PutObject return parameters for the expectation previously defined by the When method
func (e *MediaStoragePortMockPutObjectExpectation) Then(objectKey string, sha256Hex string, err error) *MediaStoragePortMock {
	e.results = &MediaStoragePortMockPutObjectResults{objectKey, sha256Hex, err}
	return e.mock
}

// Times sets number of times MediaStoragePort.PutObject should be invoked
func (mmPutObject *mMediaStoragePortMockPutObject) Times(n uint64) *mMediaStoragePortMockPutObject {
	if n == 0 {
		mmPutObject.mock.t.Fatalf("Times of MediaStoragePortMock.PutObject mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmPutObject.expectedInvocations, n)
	mmPutObject.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmPutObject
}

func (mmPutObject *mMediaStoragePortMockPutObject) invocationsDone() bool {
	if len(mmPutObject.expectations) == 0 && mmPutObject.defaultExpectation == nil && mmPutObject.mock.funcPutObject == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmPutObject.mock.afterPutObjectCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmPutObject.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// PutObject implements mm_port.MediaStoragePort
func (mmPutObject *MediaStoragePortMock) PutObject(ctx context.Context, objectName string, reader io.Reader, contentType string) (objectKey string, sha256Hex string, err error) {
	mm_atomic.AddUint64(&mmPutObject.beforePutObjectCounter, 1)
	defer mm_atomic.AddUint64(&mmPutObject.afterPutObjectCounter, 1)

	mmPutObject.t.Helper()

	if mmPutObject.inspectFuncPutObject != nil {
		mmPutObject.inspectFuncPutObject(ctx, objectName, reader, contentType)
	}

	mm_params := MediaStoragePortMockPutObjectParams{ctx, objectName, reader, contentType}

	// Record call args
	mmPutObject.PutObjectMock.mutex.Lock()
	mmPutObject.PutObjectMock.callArgs = append(mmPutObject.PutObjectMock.callArgs, &mm_params)
	mmPutObject.PutObjectMock.mutex.Unlock()

	for _, e := range mmPutObject.PutObjectMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.objectKey, e.results.sha256Hex, e.results.err
		}
	}

	if mmPutObject.PutObjectMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmPutObject.PutObjectMock.defaultExpectation.Counter, 1)
		mm_want := mmPutObject.PutObjectMock.defaultExpectation.params
		mm_want_ptrs := mmPutObject.PutObjectMock.defaultExpectation.paramPtrs

		mm_got := MediaStoragePortMockPutObjectParams{ctx, objectName, reader, contentType}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmPutObject.t.Errorf("MediaStoragePortMock.PutObject got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmPutObject.PutObjectMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.objectName != nil && !minimock.Equal(*mm_want_ptrs.objectName, mm_got.objectName) {
				mmPutObject.t.Errorf("MediaStoragePortMock.PutObject got unexpected parameter objectName, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmPutObject.PutObjectMock.defaultExpectation.expectationOrigins.originObjectName, *mm_want_ptrs.objectName, mm_got.objectName, minimock.Diff(*mm_want_ptrs.objectName, mm_got.objectName))
			}

			if mm_want_ptrs.reader != nil && !minimock.Equal(*mm_want_ptrs.reader, mm_got.reader) {
				mmPutObject.t.Errorf("MediaStoragePortMock.PutObject got unexpected parameter reader, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmPutObject.PutObjectMock.defaultExpectation.expectationOrigins.originReader, *mm_want_ptrs.reader, mm_got.reader, minimock.Diff(*mm_want_ptrs.reader, mm_got.reader))
			}

			if mm_want_ptrs.contentType != nil && !minimock.Equal(*mm_want_ptrs.contentType, mm_got.contentType) {
				mmPutObject.t.Errorf("MediaStoragePortMock.PutObject got unexpected parameter contentType, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmPutObject.PutObjectMock.defaultExpectation.expectationOrigins.originContentType, *mm_want_ptrs.contentType, mm_got.contentType, minimock.Diff(*mm_want_ptrs.contentType, mm_got.contentType))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmPutObject.t.Errorf("MediaStoragePortMock.PutObject got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmPutObject.PutObjectMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmPutObject.PutObjectMock.defaultExpectation.results
		if mm_results == nil {
			mmPutObject.t.Fatal("No results are set for the MediaStoragePortMock.PutObject")
		}
		return (*mm_results).objectKey, (*mm_results).sha256Hex, (*mm_results).err
	}
	if mmPutObject.funcPutObject != nil {
		return mmPutObject.funcPutObject(ctx, objectName, reader, contentType)
	}
	mmPutObject.t.Fatalf("Unexpected call to MediaStoragePortMock.PutObject. %v %v %v %v", ctx, objectName, reader, contentType)
	return
}

// PutObjectAfterCounter returns a count of finished MediaStoragePortMock.PutObject invocations
func (mmPutObject *MediaStoragePortMock) PutObjectAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPutObject.afterPutObjectCounter)
}

// PutObjectBeforeCounter returns a count of MediaStoragePortMock.PutObject invocations
func (mmPutObject *MediaStoragePortMock) PutObjectBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPutObject.beforePutObjectCounter)
}

// Calls returns a list of arguments used in each call to MediaStoragePortMock.PutObject.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmPutObject *mMediaStoragePortMockPutObject) Calls() []*MediaStoragePortMockPutObjectParams {
	mmPutObject.mutex.RLock()

	argCopy := make([]*MediaStoragePortMockPutObjectParams, len(mmPutObject.callArgs))
	copy(argCopy, mmPutObject.callArgs)

	mmPutObject.mutex.RUnlock()

	return argCopy
}

// MinimockPutObjectDone returns true if the count of the PutObject invocations corresponds
// the number of defined expectations
func (m *MediaStoragePortMock) MinimockPutObjectDone() bool {
	if m.PutObjectMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.PutObjectMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.PutObjectMock.invocationsDone()
}

// MinimockPutObjectInspect logs each unmet expectation
func (m *MediaStoragePortMock) MinimockPutObjectInspect() {
	for _, e := range m.PutObjectMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to MediaStoragePortMock.PutObject at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterPutObjectCounter := mm_atomic.LoadUint64(&m.afterPutObjectCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.PutObjectMock.defaultExpectation != nil && afterPutObjectCounter < 1 {
		if m.PutObjectMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to MediaStoragePortMock.PutObject at\n%s", m.PutObjectMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to MediaStoragePortMock.PutObject at\n%s with params: %#v", m.PutObjectMock.defaultExpectation.expectationOrigins.origin, *m.PutObjectMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcPutObject != nil && afterPutObjectCounter < 1 {
		m.t.Errorf("Expected call to MediaStoragePortMock.PutObject at\n%s", m.funcPutObjectOrigin)
	}

	if !m.PutObjectMock.invocationsDone() && afterPutObjectCounter > 0 {
		m.t.Errorf("Expected %d calls to MediaStoragePortMock.PutObject at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.PutObjectMock.expectedInvocations), m.PutObjectMock.expectedInvocationsOrigin, afterPutObjectCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *MediaStoragePortMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockDeleteObjectInspect()

			m.MinimockPutObjectInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *MediaStoragePortMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *MediaStoragePortMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockDeleteObjectDone() &&
		m.MinimockPutObjectDone()
}
