// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package portmock

//go:generate minimock -i sprezz/internal/domain/port.OutboundDispatcher -o outbound_dispatcher_mock.go -n OutboundDispatcherMock -p portmock

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// OutboundDispatcherMock implements mm_port.OutboundDispatcher
type OutboundDispatcherMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcForwardFederatedActivity          func(ctx context.Context, targetInbox string, actorKeyID string, privateKeyRSAPEM string, privateKeyEd25519PEM string, payload []byte) (err error)
	funcForwardFederatedActivityOrigin    string
	inspectFuncForwardFederatedActivity   func(ctx context.Context, targetInbox string, actorKeyID string, privateKeyRSAPEM string, privateKeyEd25519PEM string, payload []byte)
	afterForwardFederatedActivityCounter  uint64
	beforeForwardFederatedActivityCounter uint64
	ForwardFederatedActivityMock          mOutboundDispatcherMockForwardFederatedActivity
}

// NewOutboundDispatcherMock returns a mock for mm_port.OutboundDispatcher
func NewOutboundDispatcherMock(t minimock.Tester) *OutboundDispatcherMock {
	m := &OutboundDispatcherMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.ForwardFederatedActivityMock = mOutboundDispatcherMockForwardFederatedActivity{mock: m}
	m.ForwardFederatedActivityMock.callArgs = []*OutboundDispatcherMockForwardFederatedActivityParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mOutboundDispatcherMockForwardFederatedActivity struct {
	optional           bool
	mock               *OutboundDispatcherMock
	defaultExpectation *OutboundDispatcherMockForwardFederatedActivityExpectation
	expectations       []*OutboundDispatcherMockForwardFederatedActivityExpectation

	callArgs []*OutboundDispatcherMockForwardFederatedActivityParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// OutboundDispatcherMockForwardFederatedActivityExpectation specifies expectation struct of the OutboundDispatcher.ForwardFederatedActivity
type OutboundDispatcherMockForwardFederatedActivityExpectation struct {
	mock               *OutboundDispatcherMock
	params             *OutboundDispatcherMockForwardFederatedActivityParams
	paramPtrs          *OutboundDispatcherMockForwardFederatedActivityParamPtrs
	expectationOrigins OutboundDispatcherMockForwardFederatedActivityExpectationOrigins
	results            *OutboundDispatcherMockForwardFederatedActivityResults
	returnOrigin       string
	Counter            uint64
}

// OutboundDispatcherMockForwardFederatedActivityParams contains parameters of the OutboundDispatcher.ForwardFederatedActivity
type OutboundDispatcherMockForwardFederatedActivityParams struct {
	ctx                  context.Context
	targetInbox          string
	actorKeyID           string
	privateKeyRSAPEM     string
	privateKeyEd25519PEM string
	payload              []byte
}

// OutboundDispatcherMockForwardFederatedActivityParamPtrs contains pointers to parameters of the OutboundDispatcher.ForwardFederatedActivity
type OutboundDispatcherMockForwardFederatedActivityParamPtrs struct {
	ctx                  *context.Context
	targetInbox          *string
	actorKeyID           *string
	privateKeyRSAPEM     *string
	privateKeyEd25519PEM *string
	payload              *[]byte
}

// OutboundDispatcherMockForwardFederatedActivityResults contains results of the OutboundDispatcher.ForwardFederatedActivity
type OutboundDispatcherMockForwardFederatedActivityResults struct {
	err error
}

// OutboundDispatcherMockForwardFederatedActivityOrigins contains origins of expectations of the OutboundDispatcher.ForwardFederatedActivity
type OutboundDispatcherMockForwardFederatedActivityExpectationOrigins struct {
	origin                     string
	originCtx                  string
	originTargetInbox          string
	originActorKeyID           string
	originPrivateKeyRSAPEM     string
	originPrivateKeyEd25519PEM string
	originPayload              string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmForwardFederatedActivity *mOutboundDispatcherMockForwardFederatedActivity) Optional() *mOutboundDispatcherMockForwardFederatedActivity {
	mmForwardFederatedActivity.optional = true
	return mmForwardFederatedActivity
}

// Expect sets up expected params for OutboundDispatcher.ForwardFederatedActivity
func (mmForwardFederatedActivity *mOutboundDispatcherMockForwardFederatedActivity) Expect(ctx context.Context, targetInbox string, actorKeyID string, privateKeyRSAPEM string, privateKeyEd25519PEM string, payload []byte) *mOutboundDispatcherMockForwardFederatedActivity {
	if mmForwardFederatedActivity.mock.funcForwardFederatedActivity != nil {
		mmForwardFederatedActivity.mock.t.Fatalf("OutboundDispatcherMock.ForwardFederatedActivity mock is already set by Set")
	}

	if mmForwardFederatedActivity.defaultExpectation == nil {
		mmForwardFederatedActivity.defaultExpectation = &OutboundDispatcherMockForwardFederatedActivityExpectation{}
	}

	if mmForwardFederatedActivity.defaultExpectation.paramPtrs != nil {
		mmForwardFederatedActivity.mock.t.Fatalf("OutboundDispatcherMock.ForwardFederatedActivity mock is already set by ExpectParams functions")
	}

	mmForwardFederatedActivity.defaultExpectation.params = &OutboundDispatcherMockForwardFederatedActivityParams{ctx, targetInbox, actorKeyID, privateKeyRSAPEM, privateKeyEd25519PEM, payload}
	mmForwardFederatedActivity.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmForwardFederatedActivity.expectations {
		if minimock.Equal(e.params, mmForwardFederatedActivity.defaultExpectation.params) {
			mmForwardFederatedActivity.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmForwardFederatedActivity.defaultExpectation.params)
		}
	}

	return mmForwardFederatedActivity
}

// ExpectCtxParam1 sets up expected param ctx for OutboundDispatcher.ForwardFederatedActivity
func (mmForwardFederatedActivity *mOutboundDispatcherMockForwardFederatedActivity) ExpectCtxParam1(ctx context.Context) *mOutboundDispatcherMockForwardFederatedActivity {
	if mmForwardFederatedActivity.mock.funcForwardFederatedActivity != nil {
		mmForwardFederatedActivity.mock.t.Fatalf("OutboundDispatcherMock.ForwardFederatedActivity mock is already set by Set")
	}

	if mmForwardFederatedActivity.defaultExpectation == nil {
		mmForwardFederatedActivity.defaultExpectation = &OutboundDispatcherMockForwardFederatedActivityExpectation{}
	}

	if mmForwardFederatedActivity.defaultExpectation.params != nil {
		mmForwardFederatedActivity.mock.t.Fatalf("OutboundDispatcherMock.ForwardFederatedActivity mock is already set by Expect")
	}

	if mmForwardFederatedActivity.defaultExpectation.paramPtrs == nil {
		mmForwardFederatedActivity.defaultExpectation.paramPtrs = &OutboundDispatcherMockForwardFederatedActivityParamPtrs{}
	}
	mmForwardFederatedActivity.defaultExpectation.paramPtrs.ctx = &ctx
	mmForwardFederatedActivity.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmForwardFederatedActivity
}

// ExpectTargetInboxParam2 sets up expected param targetInbox for OutboundDispatcher.ForwardFederatedActivity
func (mmForwardFederatedActivity *mOutboundDispatcherMockForwardFederatedActivity) ExpectTargetInboxParam2(targetInbox string) *mOutboundDispatcherMockForwardFederatedActivity {
	if mmForwardFederatedActivity.mock.funcForwardFederatedActivity != nil {
		mmForwardFederatedActivity.mock.t.Fatalf("OutboundDispatcherMock.ForwardFederatedActivity mock is already set by Set")
	}

	if mmForwardFederatedActivity.defaultExpectation == nil {
		mmForwardFederatedActivity.defaultExpectation = &OutboundDispatcherMockForwardFederatedActivityExpectation{}
	}

	if mmForwardFederatedActivity.defaultExpectation.params != nil {
		mmForwardFederatedActivity.mock.t.Fatalf("OutboundDispatcherMock.ForwardFederatedActivity mock is already set by Expect")
	}

	if mmForwardFederatedActivity.defaultExpectation.paramPtrs == nil {
		mmForwardFederatedActivity.defaultExpectation.paramPtrs = &OutboundDispatcherMockForwardFederatedActivityParamPtrs{}
	}
	mmForwardFederatedActivity.defaultExpectation.paramPtrs.targetInbox = &targetInbox
	mmForwardFederatedActivity.defaultExpectation.expectationOrigins.originTargetInbox = minimock.CallerInfo(1)

	return mmForwardFederatedActivity
}

// ExpectActorKeyIDParam3 sets up expected param actorKeyID for OutboundDispatcher.ForwardFederatedActivity
func (mmForwardFederatedActivity *mOutboundDispatcherMockForwardFederatedActivity) ExpectActorKeyIDParam3(actorKeyID string) *mOutboundDispatcherMockForwardFederatedActivity {
	if mmForwardFederatedActivity.mock.funcForwardFederatedActivity != nil {
		mmForwardFederatedActivity.mock.t.Fatalf("OutboundDispatcherMock.ForwardFederatedActivity mock is already set by Set")
	}

	if mmForwardFederatedActivity.defaultExpectation == nil {
		mmForwardFederatedActivity.defaultExpectation = &OutboundDispatcherMockForwardFederatedActivityExpectation{}
	}

	if mmForwardFederatedActivity.defaultExpectation.params != nil {
		mmForwardFederatedActivity.mock.t.Fatalf("OutboundDispatcherMock.ForwardFederatedActivity mock is already set by Expect")
	}

	if mmForwardFederatedActivity.defaultExpectation.paramPtrs == nil {
		mmForwardFederatedActivity.defaultExpectation.paramPtrs = &OutboundDispatcherMockForwardFederatedActivityParamPtrs{}
	}
	mmForwardFederatedActivity.defaultExpectation.paramPtrs.actorKeyID = &actorKeyID
	mmForwardFederatedActivity.defaultExpectation.expectationOrigins.originActorKeyID = minimock.CallerInfo(1)

	return mmForwardFederatedActivity
}

// ExpectPrivateKeyRSAPEMParam4 sets up expected param privateKeyRSAPEM for OutboundDispatcher.ForwardFederatedActivity
func (mmForwardFederatedActivity *mOutboundDispatcherMockForwardFederatedActivity) ExpectPrivateKeyRSAPEMParam4(privateKeyRSAPEM string) *mOutboundDispatcherMockForwardFederatedActivity {
	if mmForwardFederatedActivity.mock.funcForwardFederatedActivity != nil {
		mmForwardFederatedActivity.mock.t.Fatalf("OutboundDispatcherMock.ForwardFederatedActivity mock is already set by Set")
	}

	if mmForwardFederatedActivity.defaultExpectation == nil {
		mmForwardFederatedActivity.defaultExpectation = &OutboundDispatcherMockForwardFederatedActivityExpectation{}
	}

	if mmForwardFederatedActivity.defaultExpectation.params != nil {
		mmForwardFederatedActivity.mock.t.Fatalf("OutboundDispatcherMock.ForwardFederatedActivity mock is already set by Expect")
	}

	if mmForwardFederatedActivity.defaultExpectation.paramPtrs == nil {
		mmForwardFederatedActivity.defaultExpectation.paramPtrs = &OutboundDispatcherMockForwardFederatedActivityParamPtrs{}
	}
	mmForwardFederatedActivity.defaultExpectation.paramPtrs.privateKeyRSAPEM = &privateKeyRSAPEM
	mmForwardFederatedActivity.defaultExpectation.expectationOrigins.originPrivateKeyRSAPEM = minimock.CallerInfo(1)

	return mmForwardFederatedActivity
}

// ExpectPrivateKeyEd25519PEMParam5 sets up expected param privateKeyEd25519PEM for OutboundDispatcher.ForwardFederatedActivity
func (mmForwardFederatedActivity *mOutboundDispatcherMockForwardFederatedActivity) ExpectPrivateKeyEd25519PEMParam5(privateKeyEd25519PEM string) *mOutboundDispatcherMockForwardFederatedActivity {
	if mmForwardFederatedActivity.mock.funcForwardFederatedActivity != nil {
		mmForwardFederatedActivity.mock.t.Fatalf("OutboundDispatcherMock.ForwardFederatedActivity mock is already set by Set")
	}

	if mmForwardFederatedActivity.defaultExpectation == nil {
		mmForwardFederatedActivity.defaultExpectation = &OutboundDispatcherMockForwardFederatedActivityExpectation{}
	}

	if mmForwardFederatedActivity.defaultExpectation.params != nil {
		mmForwardFederatedActivity.mock.t.Fatalf("OutboundDispatcherMock.ForwardFederatedActivity mock is already set by Expect")
	}

	if mmForwardFederatedActivity.defaultExpectation.paramPtrs == nil {
		mmForwardFederatedActivity.defaultExpectation.paramPtrs = &OutboundDispatcherMockForwardFederatedActivityParamPtrs{}
	}
	mmForwardFederatedActivity.defaultExpectation.paramPtrs.privateKeyEd25519PEM = &privateKeyEd25519PEM
	mmForwardFederatedActivity.defaultExpectation.expectationOrigins.originPrivateKeyEd25519PEM = minimock.CallerInfo(1)

	return mmForwardFederatedActivity
}

// ExpectPayloadParam6 sets up expected param payload for OutboundDispatcher.ForwardFederatedActivity
func (mmForwardFederatedActivity *mOutboundDispatcherMockForwardFederatedActivity) ExpectPayloadParam6(payload []byte) *mOutboundDispatcherMockForwardFederatedActivity {
	if mmForwardFederatedActivity.mock.funcForwardFederatedActivity != nil {
		mmForwardFederatedActivity.mock.t.Fatalf("OutboundDispatcherMock.ForwardFederatedActivity mock is already set by Set")
	}

	if mmForwardFederatedActivity.defaultExpectation == nil {
		mmForwardFederatedActivity.defaultExpectation = &OutboundDispatcherMockForwardFederatedActivityExpectation{}
	}

	if mmForwardFederatedActivity.defaultExpectation.params != nil {
		mmForwardFederatedActivity.mock.t.Fatalf("OutboundDispatcherMock.ForwardFederatedActivity mock is already set by Expect")
	}

	if mmForwardFederatedActivity.defaultExpectation.paramPtrs == nil {
		mmForwardFederatedActivity.defaultExpectation.paramPtrs = &OutboundDispatcherMockForwardFederatedActivityParamPtrs{}
	}
	mmForwardFederatedActivity.defaultExpectation.paramPtrs.payload = &payload
	mmForwardFederatedActivity.defaultExpectation.expectationOrigins.originPayload = minimock.CallerInfo(1)

	return mmForwardFederatedActivity
}

// Inspect accepts an inspector function that has same arguments as the OutboundDispatcher.ForwardFederatedActivity
func (mmForwardFederatedActivity *mOutboundDispatcherMockForwardFederatedActivity) Inspect(f func(ctx context.Context, targetInbox string, actorKeyID string, privateKeyRSAPEM string, privateKeyEd25519PEM string, payload []byte)) *mOutboundDispatcherMockForwardFederatedActivity {
	if mmForwardFederatedActivity.mock.inspectFuncForwardFederatedActivity != nil {
		mmForwardFederatedActivity.mock.t.Fatalf("Inspect function is already set for OutboundDispatcherMock.ForwardFederatedActivity")
	}

	mmForwardFederatedActivity.mock.inspectFuncForwardFederatedActivity = f

	return mmForwardFederatedActivity
}

// Return sets up results that will be returned by OutboundDispatcher.ForwardFederatedActivity
func (mmForwardFederatedActivity *mOutboundDispatcherMockForwardFederatedActivity) Return(err error) *OutboundDispatcherMock {
	if mmForwardFederatedActivity.mock.funcForwardFederatedActivity != nil {
		mmForwardFederatedActivity.mock.t.Fatalf("OutboundDispatcherMock.ForwardFederatedActivity mock is already set by Set")
	}

	if mmForwardFederatedActivity.defaultExpectation == nil {
		mmForwardFederatedActivity.defaultExpectation = &OutboundDispatcherMockForwardFederatedActivityExpectation{mock: mmForwardFederatedActivity.mock}
	}
	mmForwardFederatedActivity.defaultExpectation.results = &OutboundDispatcherMockForwardFederatedActivityResults{err}
	mmForwardFederatedActivity.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmForwardFederatedActivity.mock
}

// Set uses given function f to mock the OutboundDispatcher.ForwardFederatedActivity method
func (mmForwardFederatedActivity *mOutboundDispatcherMockForwardFederatedActivity) Set(f func(ctx context.Context, targetInbox string, actorKeyID string, privateKeyRSAPEM string, privateKeyEd25519PEM string, payload []byte) (err error)) *OutboundDispatcherMock {
	if mmForwardFederatedActivity.defaultExpectation != nil {
		mmForwardFederatedActivity.mock.t.Fatalf("Default expectation is already set for the OutboundDispatcher.ForwardFederatedActivity method")
	}

	if len(mmForwardFederatedActivity.expectations) > 0 {
		mmForwardFederatedActivity.mock.t.Fatalf("Some expectations are already set for the OutboundDispatcher.ForwardFederatedActivity method")
	}

	mmForwardFederatedActivity.mock.funcForwardFederatedActivity = f
	mmForwardFederatedActivity.mock.funcForwardFederatedActivityOrigin = minimock.CallerInfo(1)
	return mmForwardFederatedActivity.mock
}

// When sets expectation for the OutboundDispatcher.ForwardFederatedActivity which will trigger the result defined by the following
// Then helper
func (mmForwardFederatedActivity *mOutboundDispatcherMockForwardFederatedActivity) When(ctx context.Context, targetInbox string, actorKeyID string, privateKeyRSAPEM string, privateKeyEd25519PEM string, payload []byte) *OutboundDispatcherMockForwardFederatedActivityExpectation {
	if mmForwardFederatedActivity.mock.funcForwardFederatedActivity != nil {
		mmForwardFederatedActivity.mock.t.Fatalf("OutboundDispatcherMock.ForwardFederatedActivity mock is already set by Set")
	}

	expectation := &OutboundDispatcherMockForwardFederatedActivityExpectation{
		mock:               mmForwardFederatedActivity.mock,
		params:             &OutboundDispatcherMockForwardFederatedActivityParams{ctx, targetInbox, actorKeyID, privateKeyRSAPEM, privateKeyEd25519PEM, payload},
		expectationOrigins: OutboundDispatcherMockForwardFederatedActivityExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmForwardFederatedActivity.expectations = append(mmForwardFederatedActivity.expectations, expectation)
	return expectation
}

// Then sets up OutboundDispatcher.ForwardFederatedActivity return parameters for the expectation previously defined by the When method
func (e *OutboundDispatcherMockForwardFederatedActivityExpectation) Then(err error) *OutboundDispatcherMock {
	e.results = &OutboundDispatcherMockForwardFederatedActivityResults{err}
	return e.mock
}

// Times sets number of times OutboundDispatcher.ForwardFederatedActivity should be invoked
func (mmForwardFederatedActivity *mOutboundDispatcherMockForwardFederatedActivity) Times(n uint64) *mOutboundDispatcherMockForwardFederatedActivity {
	if n == 0 {
		mmForwardFederatedActivity.mock.t.Fatalf("Times of OutboundDispatcherMock.ForwardFederatedActivity mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmForwardFederatedActivity.expectedInvocations, n)
	mmForwardFederatedActivity.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmForwardFederatedActivity
}

func (mmForwardFederatedActivity *mOutboundDispatcherMockForwardFederatedActivity) invocationsDone() bool {
	if len(mmForwardFederatedActivity.expectations) == 0 && mmForwardFederatedActivity.defaultExpectation == nil && mmForwardFederatedActivity.mock.funcForwardFederatedActivity == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmForwardFederatedActivity.mock.afterForwardFederatedActivityCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmForwardFederatedActivity.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ForwardFederatedActivity implements mm_port.OutboundDispatcher
func (mmForwardFederatedActivity *OutboundDispatcherMock) ForwardFederatedActivity(ctx context.Context, targetInbox string, actorKeyID string, privateKeyRSAPEM string, privateKeyEd25519PEM string, payload []byte) (err error) {
	mm_atomic.AddUint64(&mmForwardFederatedActivity.beforeForwardFederatedActivityCounter, 1)
	defer mm_atomic.AddUint64(&mmForwardFederatedActivity.afterForwardFederatedActivityCounter, 1)

	mmForwardFederatedActivity.t.Helper()

	if mmForwardFederatedActivity.inspectFuncForwardFederatedActivity != nil {
		mmForwardFederatedActivity.inspectFuncForwardFederatedActivity(ctx, targetInbox, actorKeyID, privateKeyRSAPEM, privateKeyEd25519PEM, payload)
	}

	mm_params := OutboundDispatcherMockForwardFederatedActivityParams{ctx, targetInbox, actorKeyID, privateKeyRSAPEM, privateKeyEd25519PEM, payload}

	// Record call args
	mmForwardFederatedActivity.ForwardFederatedActivityMock.mutex.Lock()
	mmForwardFederatedActivity.ForwardFederatedActivityMock.callArgs = append(mmForwardFederatedActivity.ForwardFederatedActivityMock.callArgs, &mm_params)
	mmForwardFederatedActivity.ForwardFederatedActivityMock.mutex.Unlock()

	for _, e := range mmForwardFederatedActivity.ForwardFederatedActivityMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmForwardFederatedActivity.ForwardFederatedActivityMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmForwardFederatedActivity.ForwardFederatedActivityMock.defaultExpectation.Counter, 1)
		mm_want := mmForwardFederatedActivity.ForwardFederatedActivityMock.defaultExpectation.params
		mm_want_ptrs := mmForwardFederatedActivity.ForwardFederatedActivityMock.defaultExpectation.paramPtrs

		mm_got := OutboundDispatcherMockForwardFederatedActivityParams{ctx, targetInbox, actorKeyID, privateKeyRSAPEM, privateKeyEd25519PEM, payload}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmForwardFederatedActivity.t.Errorf("OutboundDispatcherMock.ForwardFederatedActivity got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmForwardFederatedActivity.ForwardFederatedActivityMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.targetInbox != nil && !minimock.Equal(*mm_want_ptrs.targetInbox, mm_got.targetInbox) {
				mmForwardFederatedActivity.t.Errorf("OutboundDispatcherMock.ForwardFederatedActivity got unexpected parameter targetInbox, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmForwardFederatedActivity.ForwardFederatedActivityMock.defaultExpectation.expectationOrigins.originTargetInbox, *mm_want_ptrs.targetInbox, mm_got.targetInbox, minimock.Diff(*mm_want_ptrs.targetInbox, mm_got.targetInbox))
			}

			if mm_want_ptrs.actorKeyID != nil && !minimock.Equal(*mm_want_ptrs.actorKeyID, mm_got.actorKeyID) {
				mmForwardFederatedActivity.t.Errorf("OutboundDispatcherMock.ForwardFederatedActivity got unexpected parameter actorKeyID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmForwardFederatedActivity.ForwardFederatedActivityMock.defaultExpectation.expectationOrigins.originActorKeyID, *mm_want_ptrs.actorKeyID, mm_got.actorKeyID, minimock.Diff(*mm_want_ptrs.actorKeyID, mm_got.actorKeyID))
			}

			if mm_want_ptrs.privateKeyRSAPEM != nil && !minimock.Equal(*mm_want_ptrs.privateKeyRSAPEM, mm_got.privateKeyRSAPEM) {
				mmForwardFederatedActivity.t.Errorf("OutboundDispatcherMock.ForwardFederatedActivity got unexpected parameter privateKeyRSAPEM, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmForwardFederatedActivity.ForwardFederatedActivityMock.defaultExpectation.expectationOrigins.originPrivateKeyRSAPEM, *mm_want_ptrs.privateKeyRSAPEM, mm_got.privateKeyRSAPEM, minimock.Diff(*mm_want_ptrs.privateKeyRSAPEM, mm_got.privateKeyRSAPEM))
			}

			if mm_want_ptrs.privateKeyEd25519PEM != nil && !minimock.Equal(*mm_want_ptrs.privateKeyEd25519PEM, mm_got.privateKeyEd25519PEM) {
				mmForwardFederatedActivity.t.Errorf("OutboundDispatcherMock.ForwardFederatedActivity got unexpected parameter privateKeyEd25519PEM, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmForwardFederatedActivity.ForwardFederatedActivityMock.defaultExpectation.expectationOrigins.originPrivateKeyEd25519PEM, *mm_want_ptrs.privateKeyEd25519PEM, mm_got.privateKeyEd25519PEM, minimock.Diff(*mm_want_ptrs.privateKeyEd25519PEM, mm_got.privateKeyEd25519PEM))
			}

			if mm_want_ptrs.payload != nil && !minimock.Equal(*mm_want_ptrs.payload, mm_got.payload) {
				mmForwardFederatedActivity.t.Errorf("OutboundDispatcherMock.ForwardFederatedActivity got unexpected parameter payload, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmForwardFederatedActivity.ForwardFederatedActivityMock.defaultExpectation.expectationOrigins.originPayload, *mm_want_ptrs.payload, mm_got.payload, minimock.Diff(*mm_want_ptrs.payload, mm_got.payload))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmForwardFederatedActivity.t.Errorf("OutboundDispatcherMock.ForwardFederatedActivity got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmForwardFederatedActivity.ForwardFederatedActivityMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmForwardFederatedActivity.ForwardFederatedActivityMock.defaultExpectation.results
		if mm_results == nil {
			mmForwardFederatedActivity.t.Fatal("No results are set for the OutboundDispatcherMock.ForwardFederatedActivity")
		}
		return (*mm_results).err
	}
	if mmForwardFederatedActivity.funcForwardFederatedActivity != nil {
		return mmForwardFederatedActivity.funcForwardFederatedActivity(ctx, targetInbox, actorKeyID, privateKeyRSAPEM, privateKeyEd25519PEM, payload)
	}
	mmForwardFederatedActivity.t.Fatalf("Unexpected call to OutboundDispatcherMock.ForwardFederatedActivity. %v %v %v %v %v %v", ctx, targetInbox, actorKeyID, privateKeyRSAPEM, privateKeyEd25519PEM, payload)
	return
}

// ForwardFederatedActivityAfterCounter returns a count of finished OutboundDispatcherMock.ForwardFederatedActivity invocations
func (mmForwardFederatedActivity *OutboundDispatcherMock) ForwardFederatedActivityAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmForwardFederatedActivity.afterForwardFederatedActivityCounter)
}

// ForwardFederatedActivityBeforeCounter returns a count of OutboundDispatcherMock.ForwardFederatedActivity invocations
func (mmForwardFederatedActivity *OutboundDispatcherMock) ForwardFederatedActivityBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmForwardFederatedActivity.beforeForwardFederatedActivityCounter)
}

// Calls returns a list of arguments used in each call to OutboundDispatcherMock.ForwardFederatedActivity.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmForwardFederatedActivity *mOutboundDispatcherMockForwardFederatedActivity) Calls() []*OutboundDispatcherMockForwardFederatedActivityParams {
	mmForwardFederatedActivity.mutex.RLock()

	argCopy := make([]*OutboundDispatcherMockForwardFederatedActivityParams, len(mmForwardFederatedActivity.callArgs))
	copy(argCopy, mmForwardFederatedActivity.callArgs)

	mmForwardFederatedActivity.mutex.RUnlock()

	return argCopy
}

// MinimockForwardFederatedActivityDone returns true if the count of the ForwardFederatedActivity invocations corresponds
// the number of defined expectations
func (m *OutboundDispatcherMock) MinimockForwardFederatedActivityDone() bool {
	if m.ForwardFederatedActivityMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ForwardFederatedActivityMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ForwardFederatedActivityMock.invocationsDone()
}

// MinimockForwardFederatedActivityInspect logs each unmet expectation
func (m *OutboundDispatcherMock) MinimockForwardFederatedActivityInspect() {
	for _, e := range m.ForwardFederatedActivityMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to OutboundDispatcherMock.ForwardFederatedActivity at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterForwardFederatedActivityCounter := mm_atomic.LoadUint64(&m.afterForwardFederatedActivityCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ForwardFederatedActivityMock.defaultExpectation != nil && afterForwardFederatedActivityCounter < 1 {
		if m.ForwardFederatedActivityMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to OutboundDispatcherMock.ForwardFederatedActivity at\n%s", m.ForwardFederatedActivityMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to OutboundDispatcherMock.ForwardFederatedActivity at\n%s with params: %#v", m.ForwardFederatedActivityMock.defaultExpectation.expectationOrigins.origin, *m.ForwardFederatedActivityMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcForwardFederatedActivity != nil && afterForwardFederatedActivityCounter < 1 {
		m.t.Errorf("Expected call to OutboundDispatcherMock.ForwardFederatedActivity at\n%s", m.funcForwardFederatedActivityOrigin)
	}

	if !m.ForwardFederatedActivityMock.invocationsDone() && afterForwardFederatedActivityCounter > 0 {
		m.t.Errorf("Expected %d calls to OutboundDispatcherMock.ForwardFederatedActivity at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ForwardFederatedActivityMock.expectedInvocations), m.ForwardFederatedActivityMock.expectedInvocationsOrigin, afterForwardFederatedActivityCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *OutboundDispatcherMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockForwardFederatedActivityInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *OutboundDispatcherMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *OutboundDispatcherMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockForwardFederatedActivityDone()
}
