// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package portmock

//go:generate minimock -i sprezz/internal/domain/port.RemoteFetcher -o remote_fetcher_mock.go -n RemoteFetcherMock -p portmock

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// RemoteFetcherMock implements mm_port.RemoteFetcher
type RemoteFetcherMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcFetchSigned          func(ctx context.Context, targetURL string, keyID string, privateKeyRSAPEM string, privateKeyEd25519PEM string) (ba1 []byte, err error)
	funcFetchSignedOrigin    string
	inspectFuncFetchSigned   func(ctx context.Context, targetURL string, keyID string, privateKeyRSAPEM string, privateKeyEd25519PEM string)
	afterFetchSignedCounter  uint64
	beforeFetchSignedCounter uint64
	FetchSignedMock          mRemoteFetcherMockFetchSigned
}

// NewRemoteFetcherMock returns a mock for mm_port.RemoteFetcher
func NewRemoteFetcherMock(t minimock.Tester) *RemoteFetcherMock {
	m := &RemoteFetcherMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.FetchSignedMock = mRemoteFetcherMockFetchSigned{mock: m}
	m.FetchSignedMock.callArgs = []*RemoteFetcherMockFetchSignedParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mRemoteFetcherMockFetchSigned struct {
	optional           bool
	mock               *RemoteFetcherMock
	defaultExpectation *RemoteFetcherMockFetchSignedExpectation
	expectations       []*RemoteFetcherMockFetchSignedExpectation

	callArgs []*RemoteFetcherMockFetchSignedParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RemoteFetcherMockFetchSignedExpectation specifies expectation struct of the RemoteFetcher.FetchSigned
type RemoteFetcherMockFetchSignedExpectation struct {
	mock               *RemoteFetcherMock
	params             *RemoteFetcherMockFetchSignedParams
	paramPtrs          *RemoteFetcherMockFetchSignedParamPtrs
	expectationOrigins RemoteFetcherMockFetchSignedExpectationOrigins
	results            *RemoteFetcherMockFetchSignedResults
	returnOrigin       string
	Counter            uint64
}

// RemoteFetcherMockFetchSignedParams contains parameters of the RemoteFetcher.FetchSigned
type RemoteFetcherMockFetchSignedParams struct {
	ctx                  context.Context
	targetURL            string
	keyID                string
	privateKeyRSAPEM     string
	privateKeyEd25519PEM string
}

// RemoteFetcherMockFetchSignedParamPtrs contains pointers to parameters of the RemoteFetcher.FetchSigned
type RemoteFetcherMockFetchSignedParamPtrs struct {
	ctx                  *context.Context
	targetURL            *string
	keyID                *string
	privateKeyRSAPEM     *string
	privateKeyEd25519PEM *string
}

// RemoteFetcherMockFetchSignedResults contains results of the RemoteFetcher.FetchSigned
type RemoteFetcherMockFetchSignedResults struct {
	ba1 []byte
	err error
}

// RemoteFetcherMockFetchSignedOrigins contains origins of expectations of the RemoteFetcher.FetchSigned
type RemoteFetcherMockFetchSignedExpectationOrigins struct {
	origin                     string
	originCtx                  string
	originTargetURL            string
	originKeyID                string
	originPrivateKeyRSAPEM     string
	originPrivateKeyEd25519PEM string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmFetchSigned *mRemoteFetcherMockFetchSigned) Optional() *mRemoteFetcherMockFetchSigned {
	mmFetchSigned.optional = true
	return mmFetchSigned
}

// Expect sets up expected params for RemoteFetcher.FetchSigned
func (mmFetchSigned *mRemoteFetcherMockFetchSigned) Expect(ctx context.Context, targetURL string, keyID string, privateKeyRSAPEM string, privateKeyEd25519PEM string) *mRemoteFetcherMockFetchSigned {
	if mmFetchSigned.mock.funcFetchSigned != nil {
		mmFetchSigned.mock.t.Fatalf("RemoteFetcherMock.FetchSigned mock is already set by Set")
	}

	if mmFetchSigned.defaultExpectation == nil {
		mmFetchSigned.defaultExpectation = &RemoteFetcherMockFetchSignedExpectation{}
	}

	if mmFetchSigned.defaultExpectation.paramPtrs != nil {
		mmFetchSigned.mock.t.Fatalf("RemoteFetcherMock.FetchSigned mock is already set by ExpectParams functions")
	}

	mmFetchSigned.defaultExpectation.params = &RemoteFetcherMockFetchSignedParams{ctx, targetURL, keyID, privateKeyRSAPEM, privateKeyEd25519PEM}
	mmFetchSigned.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmFetchSigned.expectations {
		if minimock.Equal(e.params, mmFetchSigned.defaultExpectation.params) {
			mmFetchSigned.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmFetchSigned.defaultExpectation.params)
		}
	}

	return mmFetchSigned
}

// ExpectCtxParam1 sets up expected param ctx for RemoteFetcher.FetchSigned
func (mmFetchSigned *mRemoteFetcherMockFetchSigned) ExpectCtxParam1(ctx context.Context) *mRemoteFetcherMockFetchSigned {
	if mmFetchSigned.mock.funcFetchSigned != nil {
		mmFetchSigned.mock.t.Fatalf("RemoteFetcherMock.FetchSigned mock is already set by Set")
	}

	if mmFetchSigned.defaultExpectation == nil {
		mmFetchSigned.defaultExpectation = &RemoteFetcherMockFetchSignedExpectation{}
	}

	if mmFetchSigned.defaultExpectation.params != nil {
		mmFetchSigned.mock.t.Fatalf("RemoteFetcherMock.FetchSigned mock is already set by Expect")
	}

	if mmFetchSigned.defaultExpectation.paramPtrs == nil {
		mmFetchSigned.defaultExpectation.paramPtrs = &RemoteFetcherMockFetchSignedParamPtrs{}
	}
	mmFetchSigned.defaultExpectation.paramPtrs.ctx = &ctx
	mmFetchSigned.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmFetchSigned
}

// ExpectTargetURLParam2 sets up expected param targetURL for RemoteFetcher.FetchSigned
func (mmFetchSigned *mRemoteFetcherMockFetchSigned) ExpectTargetURLParam2(targetURL string) *mRemoteFetcherMockFetchSigned {
	if mmFetchSigned.mock.funcFetchSigned != nil {
		mmFetchSigned.mock.t.Fatalf("RemoteFetcherMock.FetchSigned mock is already set by Set")
	}

	if mmFetchSigned.defaultExpectation == nil {
		mmFetchSigned.defaultExpectation = &RemoteFetcherMockFetchSignedExpectation{}
	}

	if mmFetchSigned.defaultExpectation.params != nil {
		mmFetchSigned.mock.t.Fatalf("RemoteFetcherMock.FetchSigned mock is already set by Expect")
	}

	if mmFetchSigned.defaultExpectation.paramPtrs == nil {
		mmFetchSigned.defaultExpectation.paramPtrs = &RemoteFetcherMockFetchSignedParamPtrs{}
	}
	mmFetchSigned.defaultExpectation.paramPtrs.targetURL = &targetURL
	mmFetchSigned.defaultExpectation.expectationOrigins.originTargetURL = minimock.CallerInfo(1)

	return mmFetchSigned
}

// ExpectKeyIDParam3 sets up expected param keyID for RemoteFetcher.FetchSigned
func (mmFetchSigned *mRemoteFetcherMockFetchSigned) ExpectKeyIDParam3(keyID string) *mRemoteFetcherMockFetchSigned {
	if mmFetchSigned.mock.funcFetchSigned != nil {
		mmFetchSigned.mock.t.Fatalf("RemoteFetcherMock.FetchSigned mock is already set by Set")
	}

	if mmFetchSigned.defaultExpectation == nil {
		mmFetchSigned.defaultExpectation = &RemoteFetcherMockFetchSignedExpectation{}
	}

	if mmFetchSigned.defaultExpectation.params != nil {
		mmFetchSigned.mock.t.Fatalf("RemoteFetcherMock.FetchSigned mock is already set by Expect")
	}

	if mmFetchSigned.defaultExpectation.paramPtrs == nil {
		mmFetchSigned.defaultExpectation.paramPtrs = &RemoteFetcherMockFetchSignedParamPtrs{}
	}
	mmFetchSigned.defaultExpectation.paramPtrs.keyID = &keyID
	mmFetchSigned.defaultExpectation.expectationOrigins.originKeyID = minimock.CallerInfo(1)

	return mmFetchSigned
}

// ExpectPrivateKeyRSAPEMParam4 sets up expected param privateKeyRSAPEM for RemoteFetcher.FetchSigned
func (mmFetchSigned *mRemoteFetcherMockFetchSigned) ExpectPrivateKeyRSAPEMParam4(privateKeyRSAPEM string) *mRemoteFetcherMockFetchSigned {
	if mmFetchSigned.mock.funcFetchSigned != nil {
		mmFetchSigned.mock.t.Fatalf("RemoteFetcherMock.FetchSigned mock is already set by Set")
	}

	if mmFetchSigned.defaultExpectation == nil {
		mmFetchSigned.defaultExpectation = &RemoteFetcherMockFetchSignedExpectation{}
	}

	if mmFetchSigned.defaultExpectation.params != nil {
		mmFetchSigned.mock.t.Fatalf("RemoteFetcherMock.FetchSigned mock is already set by Expect")
	}

	if mmFetchSigned.defaultExpectation.paramPtrs == nil {
		mmFetchSigned.defaultExpectation.paramPtrs = &RemoteFetcherMockFetchSignedParamPtrs{}
	}
	mmFetchSigned.defaultExpectation.paramPtrs.privateKeyRSAPEM = &privateKeyRSAPEM
	mmFetchSigned.defaultExpectation.expectationOrigins.originPrivateKeyRSAPEM = minimock.CallerInfo(1)

	return mmFetchSigned
}

// ExpectPrivateKeyEd25519PEMParam5 sets up expected param privateKeyEd25519PEM for RemoteFetcher.FetchSigned
func (mmFetchSigned *mRemoteFetcherMockFetchSigned) ExpectPrivateKeyEd25519PEMParam5(privateKeyEd25519PEM string) *mRemoteFetcherMockFetchSigned {
	if mmFetchSigned.mock.funcFetchSigned != nil {
		mmFetchSigned.mock.t.Fatalf("RemoteFetcherMock.FetchSigned mock is already set by Set")
	}

	if mmFetchSigned.defaultExpectation == nil {
		mmFetchSigned.defaultExpectation = &RemoteFetcherMockFetchSignedExpectation{}
	}

	if mmFetchSigned.defaultExpectation.params != nil {
		mmFetchSigned.mock.t.Fatalf("RemoteFetcherMock.FetchSigned mock is already set by Expect")
	}

	if mmFetchSigned.defaultExpectation.paramPtrs == nil {
		mmFetchSigned.defaultExpectation.paramPtrs = &RemoteFetcherMockFetchSignedParamPtrs{}
	}
	mmFetchSigned.defaultExpectation.paramPtrs.privateKeyEd25519PEM = &privateKeyEd25519PEM
	mmFetchSigned.defaultExpectation.expectationOrigins.originPrivateKeyEd25519PEM = minimock.CallerInfo(1)

	return mmFetchSigned
}

// Inspect accepts an inspector function that has same arguments as the RemoteFetcher.FetchSigned
func (mmFetchSigned *mRemoteFetcherMockFetchSigned) Inspect(f func(ctx context.Context, targetURL string, keyID string, privateKeyRSAPEM string, privateKeyEd25519PEM string)) *mRemoteFetcherMockFetchSigned {
	if mmFetchSigned.mock.inspectFuncFetchSigned != nil {
		mmFetchSigned.mock.t.Fatalf("Inspect function is already set for RemoteFetcherMock.FetchSigned")
	}

	mmFetchSigned.mock.inspectFuncFetchSigned = f

	return mmFetchSigned
}

// Return sets up results that will be returned by RemoteFetcher.FetchSigned
func (mmFetchSigned *mRemoteFetcherMockFetchSigned) Return(ba1 []byte, err error) *RemoteFetcherMock {
	if mmFetchSigned.mock.funcFetchSigned != nil {
		mmFetchSigned.mock.t.Fatalf("RemoteFetcherMock.FetchSigned mock is already set by Set")
	}

	if mmFetchSigned.defaultExpectation == nil {
		mmFetchSigned.defaultExpectation = &RemoteFetcherMockFetchSignedExpectation{mock: mmFetchSigned.mock}
	}
	mmFetchSigned.defaultExpectation.results = &RemoteFetcherMockFetchSignedResults{ba1, err}
	mmFetchSigned.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmFetchSigned.mock
}

// Set uses given function f to mock the RemoteFetcher.FetchSigned method
func (mmFetchSigned *mRemoteFetcherMockFetchSigned) Set(f func(ctx context.Context, targetURL string, keyID string, privateKeyRSAPEM string, privateKeyEd25519PEM string) (ba1 []byte, err error)) *RemoteFetcherMock {
	if mmFetchSigned.defaultExpectation != nil {
		mmFetchSigned.mock.t.Fatalf("Default expectation is already set for the RemoteFetcher.FetchSigned method")
	}

	if len(mmFetchSigned.expectations) > 0 {
		mmFetchSigned.mock.t.Fatalf("Some expectations are already set for the RemoteFetcher.FetchSigned method")
	}

	mmFetchSigned.mock.funcFetchSigned = f
	mmFetchSigned.mock.funcFetchSignedOrigin = minimock.CallerInfo(1)
	return mmFetchSigned.mock
}

// When sets expectation for the RemoteFetcher.FetchSigned which will trigger the result defined by the following
// Then helper
func (mmFetchSigned *mRemoteFetcherMockFetchSigned) When(ctx context.Context, targetURL string, keyID string, privateKeyRSAPEM string, privateKeyEd25519PEM string) *RemoteFetcherMockFetchSignedExpectation {
	if mmFetchSigned.mock.funcFetchSigned != nil {
		mmFetchSigned.mock.t.Fatalf("RemoteFetcherMock.FetchSigned mock is already set by Set")
	}

	expectation := &RemoteFetcherMockFetchSignedExpectation{
		mock:               mmFetchSigned.mock,
		params:             &RemoteFetcherMockFetchSignedParams{ctx, targetURL, keyID, privateKeyRSAPEM, privateKeyEd25519PEM},
		expectationOrigins: RemoteFetcherMockFetchSignedExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmFetchSigned.expectations = append(mmFetchSigned.expectations, expectation)
	return expectation
}

// Then sets up RemoteFetcher.FetchSigned return parameters for the expectation previously defined by the When method
func (e *RemoteFetcherMockFetchSignedExpectation) Then(ba1 []byte, err error) *RemoteFetcherMock {
	e.results = &RemoteFetcherMockFetchSignedResults{ba1, err}
	return e.mock
}

// Times sets number of times RemoteFetcher.FetchSigned should be invoked
func (mmFetchSigned *mRemoteFetcherMockFetchSigned) Times(n uint64) *mRemoteFetcherMockFetchSigned {
	if n == 0 {
		mmFetchSigned.mock.t.Fatalf("Times of RemoteFetcherMock.FetchSigned mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmFetchSigned.expectedInvocations, n)
	mmFetchSigned.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmFetchSigned
}

func (mmFetchSigned *mRemoteFetcherMockFetchSigned) invocationsDone() bool {
	if len(mmFetchSigned.expectations) == 0 && mmFetchSigned.defaultExpectation == nil && mmFetchSigned.mock.funcFetchSigned == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmFetchSigned.mock.afterFetchSignedCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmFetchSigned.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// FetchSigned implements mm_port.RemoteFetcher
func (mmFetchSigned *RemoteFetcherMock) FetchSigned(ctx context.Context, targetURL string, keyID string, privateKeyRSAPEM string, privateKeyEd25519PEM string) (ba1 []byte, err error) {
	mm_atomic.AddUint64(&mmFetchSigned.beforeFetchSignedCounter, 1)
	defer mm_atomic.AddUint64(&mmFetchSigned.afterFetchSignedCounter, 1)

	mmFetchSigned.t.Helper()

	if mmFetchSigned.inspectFuncFetchSigned != nil {
		mmFetchSigned.inspectFuncFetchSigned(ctx, targetURL, keyID, privateKeyRSAPEM, privateKeyEd25519PEM)
	}

	mm_params := RemoteFetcherMockFetchSignedParams{ctx, targetURL, keyID, privateKeyRSAPEM, privateKeyEd25519PEM}

	// Record call args
	mmFetchSigned.FetchSignedMock.mutex.Lock()
	mmFetchSigned.FetchSignedMock.callArgs = append(mmFetchSigned.FetchSignedMock.callArgs, &mm_params)
	mmFetchSigned.FetchSignedMock.mutex.Unlock()

	for _, e := range mmFetchSigned.FetchSignedMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ba1, e.results.err
		}
	}

	if mmFetchSigned.FetchSignedMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmFetchSigned.FetchSignedMock.defaultExpectation.Counter, 1)
		mm_want := mmFetchSigned.FetchSignedMock.defaultExpectation.params
		mm_want_ptrs := mmFetchSigned.FetchSignedMock.defaultExpectation.paramPtrs

		mm_got := RemoteFetcherMockFetchSignedParams{ctx, targetURL, keyID, privateKeyRSAPEM, privateKeyEd25519PEM}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmFetchSigned.t.Errorf("RemoteFetcherMock.FetchSigned got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmFetchSigned.FetchSignedMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.targetURL != nil && !minimock.Equal(*mm_want_ptrs.targetURL, mm_got.targetURL) {
				mmFetchSigned.t.Errorf("RemoteFetcherMock.FetchSigned got unexpected parameter targetURL, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmFetchSigned.FetchSignedMock.defaultExpectation.expectationOrigins.originTargetURL, *mm_want_ptrs.targetURL, mm_got.targetURL, minimock.Diff(*mm_want_ptrs.targetURL, mm_got.targetURL))
			}

			if mm_want_ptrs.keyID != nil && !minimock.Equal(*mm_want_ptrs.keyID, mm_got.keyID) {
				mmFetchSigned.t.Errorf("RemoteFetcherMock.FetchSigned got unexpected parameter keyID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmFetchSigned.FetchSignedMock.defaultExpectation.expectationOrigins.originKeyID, *mm_want_ptrs.keyID, mm_got.keyID, minimock.Diff(*mm_want_ptrs.keyID, mm_got.keyID))
			}

			if mm_want_ptrs.privateKeyRSAPEM != nil && !minimock.Equal(*mm_want_ptrs.privateKeyRSAPEM, mm_got.privateKeyRSAPEM) {
				mmFetchSigned.t.Errorf("RemoteFetcherMock.FetchSigned got unexpected parameter privateKeyRSAPEM, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmFetchSigned.FetchSignedMock.defaultExpectation.expectationOrigins.originPrivateKeyRSAPEM, *mm_want_ptrs.privateKeyRSAPEM, mm_got.privateKeyRSAPEM, minimock.Diff(*mm_want_ptrs.privateKeyRSAPEM, mm_got.privateKeyRSAPEM))
			}

			if mm_want_ptrs.privateKeyEd25519PEM != nil && !minimock.Equal(*mm_want_ptrs.privateKeyEd25519PEM, mm_got.privateKeyEd25519PEM) {
				mmFetchSigned.t.Errorf("RemoteFetcherMock.FetchSigned got unexpected parameter privateKeyEd25519PEM, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmFetchSigned.FetchSignedMock.defaultExpectation.expectationOrigins.originPrivateKeyEd25519PEM, *mm_want_ptrs.privateKeyEd25519PEM, mm_got.privateKeyEd25519PEM, minimock.Diff(*mm_want_ptrs.privateKeyEd25519PEM, mm_got.privateKeyEd25519PEM))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmFetchSigned.t.Errorf("RemoteFetcherMock.FetchSigned got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmFetchSigned.FetchSignedMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmFetchSigned.FetchSignedMock.defaultExpectation.results
		if mm_results == nil {
			mmFetchSigned.t.Fatal("No results are set for the RemoteFetcherMock.FetchSigned")
		}
		return (*mm_results).ba1, (*mm_results).err
	}
	if mmFetchSigned.funcFetchSigned != nil {
		return mmFetchSigned.funcFetchSigned(ctx, targetURL, keyID, privateKeyRSAPEM, privateKeyEd25519PEM)
	}
	mmFetchSigned.t.Fatalf("Unexpected call to RemoteFetcherMock.FetchSigned. %v %v %v %v %v", ctx, targetURL, keyID, privateKeyRSAPEM, privateKeyEd25519PEM)
	return
}

// FetchSignedAfterCounter returns a count of finished RemoteFetcherMock.FetchSigned invocations
func (mmFetchSigned *RemoteFetcherMock) FetchSignedAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmFetchSigned.afterFetchSignedCounter)
}

// FetchSignedBeforeCounter returns a count of RemoteFetcherMock.FetchSigned invocations
func (mmFetchSigned *RemoteFetcherMock) FetchSignedBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmFetchSigned.beforeFetchSignedCounter)
}

// Calls returns a list of arguments used in each call to RemoteFetcherMock.FetchSigned.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmFetchSigned *mRemoteFetcherMockFetchSigned) Calls() []*RemoteFetcherMockFetchSignedParams {
	mmFetchSigned.mutex.RLock()

	argCopy := make([]*RemoteFetcherMockFetchSignedParams, len(mmFetchSigned.callArgs))
	copy(argCopy, mmFetchSigned.callArgs)

	mmFetchSigned.mutex.RUnlock()

	return argCopy
}

// MinimockFetchSignedDone returns true if the count of the FetchSigned invocations corresponds
// the number of defined expectations
func (m *RemoteFetcherMock) MinimockFetchSignedDone() bool {
	if m.FetchSignedMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.FetchSignedMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.FetchSignedMock.invocationsDone()
}

// MinimockFetchSignedInspect logs each unmet expectation
func (m *RemoteFetcherMock) MinimockFetchSignedInspect() {
	for _, e := range m.FetchSignedMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RemoteFetcherMock.FetchSigned at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterFetchSignedCounter := mm_atomic.LoadUint64(&m.afterFetchSignedCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.FetchSignedMock.defaultExpectation != nil && afterFetchSignedCounter < 1 {
		if m.FetchSignedMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RemoteFetcherMock.FetchSigned at\n%s", m.FetchSignedMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RemoteFetcherMock.FetchSigned at\n%s with params: %#v", m.FetchSignedMock.defaultExpectation.expectationOrigins.origin, *m.FetchSignedMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcFetchSigned != nil && afterFetchSignedCounter < 1 {
		m.t.Errorf("Expected call to RemoteFetcherMock.FetchSigned at\n%s", m.funcFetchSignedOrigin)
	}

	if !m.FetchSignedMock.invocationsDone() && afterFetchSignedCounter > 0 {
		m.t.Errorf("Expected %d calls to RemoteFetcherMock.FetchSigned at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.FetchSignedMock.expectedInvocations), m.FetchSignedMock.expectedInvocationsOrigin, afterFetchSignedCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *RemoteFetcherMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockFetchSignedInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *RemoteFetcherMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *RemoteFetcherMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockFetchSignedDone()
}
